apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  namespace: playground
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:2VnJCGtdJ8YtPwTNnSU=,iv:vqFwLgGJYCXDbDT155Ktni3CRRrsNQj8ebljnUoWQ/Q=,tag:zTmZyMXtTstX8DptlNUZ9A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0WVpGWmV6RmdlOHlJV0RE
        cmdSN1ZHWU9UM3JVUlNaN3Q2djhyNHp6aFVZClhUUUJYMTBBczhnS2J5bU91NXdG
        Qm10aVBjWVp4RFZNM0taWGpjTkpvYUEKLS0tIFltcGhmcjIwUVZ4cTJ6aEIxUGdF
        dEJaWnJMRHR4M3FubzNFOWcyK2dvQzAKqz6o9UA+3xsRI2eHqPINiAXQbko+5MsD
        IgW+swkatYTmZ5isVZkPJ7mTn9mkeUFcQ1kuB+d7ASQy41T8BApXSQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1m8j9egmweu9c8cpz2yejsulpzy82227eceh9awergehk5pflwfsslu4nah
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-24T19:11:07Z"
  mac: ENC[AES256_GCM,data:YO4I3rlInreSrAMPqYdEwONjdzEq3j6JiDXWjaQnt4YkwVrbLvxR36833eypQoZfGuMhn2q7xVcCd7gj7iicF6kQXtqRjwpjwgidjh8RGTnQ7rLv2dSt8Ek/tFGN2RQgzkyQTSq6D9Wd+kcM/NjURf06b5ByXB1aFhbNg1o5pgc=,iv:bhuUcm/m81YmG5zbomVUUnyziEJCD3ezQygMzJpJHSo=,tag:c7N3btyGLbKQOQMAlLSrFA==,type:str]
  version: 3.13.0
