apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  namespace: playground
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:SgAJs00MH8jVGiEstQI=,iv:P/J9SdAdbVuMbrcwVevSBOyTxxM4N4bkE23lFTESjHY=,tag:W8uG20iXFDCR9wDzBZ2fRw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbWlSMzFJYVJDanQrL2lB
        MVE0SnhCcUlqbFQ2bDNBWmJwTkZuVmUxM2k4Cno0Q0tXTitTOU9iS2cwMHhXSzFq
        YkpEcGxUQk4wbm10WElLSkF2SVN5Q0EKLS0tIDluRTYydVlqN0plaW9tWFliUnhp
        WU82eFNaeGtBMmRjOTEzN2N4dmpZT2cKGmHc/o1A+PXRDutXBwUoxvNr0bmXLBVK
        BRP5EHIeD2d6/Invz18djge5nlucYiwxvK9z1WLtK9ayk8fIj/DiCA==
        -----END AGE ENCRYPTED FILE-----
        recipient: age1m8j9egmweu9c8cpz2yejsulpzy82227eceh9awergehk5pflwfsslu4nah
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-24T19:04:00Z"
  mac: ENC[AES256_GCM,data:l6vepSN3OxpfU4Mf1dmKLrk6sYkPQbQoRV4oLRWCbZPoq445iPOMF5RJZFhNwtZwQf1F0i+DE4+vRiZHKNLx/vigftFLuTGNvlyTIzugqVlLhxsXOaByzzDej1eVgIpfWC5bnR/WiOGXmAVW7bZcB8frxHmCf8oz7Hr0W4e06iY=,iv:KmrWFYdfM3QbmqZEhgzvfc8gR+UTBR8qK26hyrgbtoc=,tag:y4bKC4gcCKNfnIDtJuAqKw==,type:str]
  version: 3.13.0
