apiVersion: v1
kind: Secret
metadata:
  name: pve-exporter-secret
  namespace: monitoring
type: Opaque
stringData:
  pve.yml: ENC[AES256_GCM,data:cm2cKgW2tC8uGbPThAWhQRajMf2/VJRTp2vZJEUo4GFsjcA0B/AckcvnSb/MSznqd8EDaegZmayYZupIlpHBTx1dR7ikW4L0l9toPK/yWkDjDrBnrFAtXV8okIeJkaNWXQW6D3TSHRJc4B/J70Ey4g6osSapDqDQBom7JWGdv9TbEIiq95Qsf7IXiDkjlUVe,iv:G+zJf7iytYJHHeUHSXIc7XsJjZGhrANB/S9FNNdaGKY=,tag:PBB/+ICKfDwlBxAaIy/9hQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVkRKeEZwNk1VK3Jnc0dv
        QS96R28yMkd0NnJmWWVpSnRjTVgzekQ1RERzCktiVExUQy9Mb2hDWE8zbFhIajU0
        SUZOc2h0ejBOS0xRV09HVGxlODVLU1UKLS0tIEc5T1VOSmY0QTZCNEFIL3duQVZV
        NWR3aXh3MjdQckxZWkt4VUJvcElOU1kK1rGZdB/FyWNSdmUrnNxlKXF/+xS40HOE
        EoGAVoI8UQDgXTMgdZ3gcTSIJUpMyPF7zDdzBXpYYrcU9lJZLjdAuw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n0cqvlyfca7gjasrmj4668gn9e3pak8fep0e84cvnpc3srt8zffqn4fs74
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWW9ZT1pEVVpsZ3pIM0Ni
        UEwvSU9QVEorRHcwQnlmdVZFaTBvWGU1YTFFCkZDTlFlNXFKTFN3L0lsK2JZd1RZ
        SzlGSmpKNnFDbWNEL0dCUmZRdHhqY0EKLS0tIFJYZHRwVzJkNExUOXg1RjF2YnJR
        dWlET1BlcXBUY1lkQnR3R3p4eEpaSFkKXVxIdiZ3MPZYvuW2kh6ePvwdfWmG9ogM
        szMxF37mBqLSTkbjYKBcPETRhMwMcJyY6Cwiau8ILPqxeXCwkre9xA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10yse6kg99dwtsjaq4l7umdheecwsznpk4dnu76ff5jmjuka8uv9se4ysq2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T21:11:30Z"
  mac: ENC[AES256_GCM,data:1Ub5L3GuWGS87yA+59fv6rLSJI76NE+62bBdF8cfcT3bUomtW3DVARdlww74Fds7ZCJrrFvSussaScWEveGsVqZo4pnJAHJn1dJb3fALu7DEagYXWLsbVefHjOfMBbjwkErQNjPOWLWb+AuKz9jzRwS9lu1udYyUvzkelI83pic=,iv:FdmEsMTnt4DWHuHqJQQVeM2IZVHg41ZRW+kJHZhNRJ0=,tag:IImWhu2KKYqe0jhZ8CxzXQ==,type:str]
  version: 3.13.0
