apiVersion: v1
kind: Service
metadata:
  name: graphite-exporter
  namespace: monitoring
  labels:
    app: graphite-exporter
  annotations:
    metallb.io/loadBalancerIPs: "{{ .Values.homelab.serviceIps.graphiteExporter }}"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 9108
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: 9109
      targetPort: graphite-tcp
      protocol: TCP
      name: graphite-tcp
    - port: 9109
      targetPort: graphite-udp
      protocol: UDP
      name: graphite-udp
  selector:
    app: graphite-exporter
