apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  namespace: playground
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:2VnJCGtdJ8YtPwTNnSU=,iv:vqFwLgGJYCXDbDT155Ktni3CRRrsNQj8ebljnUoWQ/Q=,tag:zTmZyMXtTstX8DptlNUZ9A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUHQzTjE4eWRRUGhrQjQ0
        N3FtVTNYUXg4R08wMnR2V3g5Z1NVNTVxMHlNCjhlUU9ES1pDNUFuYUI0WXN2U2x5
        YytJc01KWkJ1ZmFYc3NleldibUIzNTAKLS0tIGRYWTFhTDd5VU5OdjIzV1lreC9v
        NDVBUHNxQUQ4dHJWaThnSTBXN3ZWcWcKdxvO6Gr/629H+jo9ReBrIgFnZPMjCkoS
        eydFCW0AqEmRCZOe+EaIcIXbexSN1LXSXB3xduRHkRH8X31xJCAfrA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n0cqvlyfca7gjasrmj4668gn9e3pak8fep0e84cvnpc3srt8zffqn4fs74
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSUxoQlJnWEhJU29naFoz
        WFhJeHk4NDJsQ0Z1d2d5YWJ1c1pwV3BvK3lNCmpqNEQ1VU14R3dRUGRYV0FiQ0tY
        V2x4cTJkY3FrMW1idHlva0VaMUhMZmMKLS0tICtZTXZLNGVZRFg3L2hySUY3SFBt
        L09RWnlQOE4yQ2hQNlZWNkdSTU85aVkKfkMWZ0YiI1pK3DDr0jZ5qr+xu3YTHMN2
        wmuZMB5m0e/obsSiNMXiFZWoU8rGBlXxvZOZvvi1q/I8em2iscReww==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10yse6kg99dwtsjaq4l7umdheecwsznpk4dnu76ff5jmjuka8uv9se4ysq2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-24T19:11:07Z"
  mac: ENC[AES256_GCM,data:YO4I3rlInreSrAMPqYdEwONjdzEq3j6JiDXWjaQnt4YkwVrbLvxR36833eypQoZfGuMhn2q7xVcCd7gj7iicF6kQXtqRjwpjwgidjh8RGTnQ7rLv2dSt8Ek/tFGN2RQgzkyQTSq6D9Wd+kcM/NjURf06b5ByXB1aFhbNg1o5pgc=,iv:bhuUcm/m81YmG5zbomVUUnyziEJCD3ezQygMzJpJHSo=,tag:c7N3btyGLbKQOQMAlLSrFA==,type:str]
  version: 3.13.0
