apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:YzPSKQzTvXDzoR3d6wYQPd0Z+uaxVVto3FJ1dcnmiuEQEpIXccxN7XuBadvqH3u99VxV+dU=,iv:wshatLVlUPNz8qrTWUDfCEW878jBJpJW/ONrU10BS+A=,tag:nBaxO0Hwe6w7NcjTFZ5lEg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZTA2blgxUVhrSHRlK2JI
        dzMxQzVEOEgwdGtWQWc0MHFhaktxKzNEYkJnCjhuU0xTSzJYci8vQ284aE4vYjhI
        ZGVJNWg1SiswRE4xVVM3MjBldlZKRUUKLS0tIEpIcE9GMlArTmhTUEFRdURlUXFu
        eU5oWjBtN09EZHZKRHhpdGRJZ0JZQVkKwU8sGvvICaHUOAchH2uqVwj/HGDuJYQb
        7wleWiOw3TEItPcNE/mWGGPlESKhZKRQsTqE02+en4IjsEg7cZOsSw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n0cqvlyfca7gjasrmj4668gn9e3pak8fep0e84cvnpc3srt8zffqn4fs74
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBseW43TW5FS3lFVUxDbEdN
        QU1Hdk9Md2sydGRkU2U4MXFZWklITUhXNkY4ClNJSU1pVFlNV1F3enBYNUVCRnFk
        YitBek9CRGpFSjVoeWp4cmJ5NVJ4TTQKLS0tICsyMW03RzZlbm1tWWZLOVpsZmd4
        bmRQTUR6OEFNM1RhNXgwbjRIZUw0cGMK7qV6YYrp6aYr9VbpuZLh8gopDX1RQLBi
        X5kQ3xRShZ219ev2IKHuR8dpDcZgulAHEy/2tHSDuO3RVhc5yx/sqA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10yse6kg99dwtsjaq4l7umdheecwsznpk4dnu76ff5jmjuka8uv9se4ysq2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-28T23:04:14Z"
  mac: ENC[AES256_GCM,data:Qpn3VhWUYt/oCBf1BRHd/B6AfxnAT6T/iTNKEmbTeZBKw1meCmeXBA8SCdxAhtZXoU1d0rCIWYRmP139F4I5Gn/EKp0arRU1Y5PDa/SSwF4NLE7po7FvmDHYJhFYPJ8pT0qID4H8sUwFoIcvoPPkL62I+3+ojyTMDwI+pjLif2M=,iv:vY3BMPoaSaDpiDLOMMqnrQupJnMN4PXylBPysD3YJUo=,tag:lTC2uYG6ZiROSpf/LqOtMA==,type:str]
  version: 3.13.1
