---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: duckdns-secret
  namespace: cert-manager
spec:
  encryptedData:
    token: AgAdZ8bl2cZQWew8yyHoMkuxBtSbUStW6r2R/YZ0+uVMYqBx+UTRbY/rWi2CE1SAfgKAXnUNdBf6asAYXdgerMGTSa8CXSNk3jXGr+h8MM352V41QLVBM6qKiPXRLmiYkeKBhQX1Q29eZKnHiZIWAdp2fCUG1H6HmuVTae5qwqGLwJ0OaesU3kAIQnbXju18pU0v9CUcc4GucGQgHYYmCZRdoRzuA1WOJhT4UasBvcD+Jc+tEUXzU3YnLINy86IN9Jg0DYGmQLWB69JawivyADbCBJt19btzd6+y2YLlbmYu83X2+lPPcrwQL0Dzct9cxYZZO8pivsemQ/BAXSVztvRK2VIouF/C60+7lVQy/owjSTcGB4AjvCL9HkzUDbhy8gZuVnnjFTZz3HVzTZdEujldtjpyMnQF6/kJaeCthNqnSCbv/vXQSJZJwd1uh5pRKw9frHeTviNmTKYrfSp3dvBYkvF3de9HDHXNLezr7KxUkjOi/wJxaqwVbGET+JGnFQUfH6aBJ8OBuYbKWwTLCW2UiRRq5cfv/gthFOfQIgC5HvBjKreme6MALFCgRlMgh/jrgOMdDRKwzZFYDtjw0pSzGx+RpW7kNGdu7AzMenZy23rG0JMxpa27IhyVG8ksE7C25jBpPr7hcHTBllbcRNDPrhvG95920wOXYEIlWg34fCJKlBqbsuZrTQx7m5zFgaY5Vh6HywpvpqUnX1YdgWkqtevLuHT4ltrO5G/FZHbdbr1x+n0=
  template:
    metadata:
      name: duckdns-secret
      namespace: cert-manager
