---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: duckdns-secret
  namespace: cert-manager
spec:
  encryptedData:
    token: AgAj2c29juTn7RDPiyCreq051iYapV54fMHhXFjNXbcol8oaACruT2wWwkQk9xn2h6fO/kolE8xi4QUb3K7uWdZjYPgkUlgTr8+iF7IFC6oYeCyIINL94qbMfjE17JQRPiuKFZWesfTeCyafC7orIAxirIGsftbLGU3W38w670fFZg+4b2TMK0BqFRfHP9LEwuqzwRmVYg6wnAnkQA2m9GXiv919czuhUtb/svzrsYq0OkwlU22oA11cs00OdNmy6ZX6oUo01Ah3QAWclVpwYXAkK74dnfpGJDNqyEUDWBsohY0P0E17Wt3cYd1CLdCcpQG3XOMGACUt5GQSS5zO3i5K5nzHvK9MRFRYqRNuRWDMN5W8/cVDZtxouF1wa1VpGEGaRkqoOwOl6itB45S6bFqdHP1qqnFeSOxyarB/hyMPQi02Q4bMoTxT2TOsvsHslMbDnKShQjjcAChCb6jAkfbS5XSMSOzukEjd2kNvYRfIJRAoUQJ2vLGJKSlOwOjJF3Er2cX9b8pZtReMnBAUEuEJXPt/re7qjGd5bdbxGave43W0w3lWEQ1R4iTXMJe537IdSMpTWzcW90z+vh7B20E7t4UnnbQf15xg1SjK8nKNvBVTa1NtRmwIzDBIzYd2npuU5uYMMueqIl6FwsyctaZlBLiNoHb/vU2GkY1GrZhL8Bkqk6b06pK8hn7aDUcmRD+jLmCyykl7arT/h8GR3dnYgHsEI72wySJT5X/vft7DezV3oU0=
  template:
    metadata:
      name: duckdns-secret
      namespace: cert-manager
