apiVersion: v1
kind: Secret
metadata:
  name: anki-sync-server-secret
  namespace: anki-sync-server
type: Opaque
stringData:
  SYNC_USER1: ENC[AES256_GCM,data:Z1bgTwT2JaHURBfcuPyOi2tSer22Ojd2Sm8gk50nCBO8PZnS703kWb+ZjucJXIc3zOods3dlEGBbeyhmRlGPmidgiRYf,iv:sVfSCekFohxFb6nDDIznm+VuyF2j/7OdVhiS/aP+Sck=,tag:1WdHn6eWXcHo21Nx11QJVw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDazZORFdyZ3VPemx5QXBl
        UEVLZkVyd3crU1N2THFRT0hSRzc4MHFwOUNjCllwMC83RDc1M1p4T3A2UWo4OEpL
        cXNrdVdnUXg1ajVycG0rcVpwNHM5L0EKLS0tIHh0Wm5IY08zMGJId2wzd3N2ajhH
        bzA0aFE0TWZ5OWlxblZJRDZGb0xFSmMKw4dh5sWbSEDJ1jWTr/5vFcf/Rez6Xonj
        ABM8c070GgGDLymgUwL4EFhnddpFVeClvmSiabSaqB9UuMO4yorwOA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n0cqvlyfca7gjasrmj4668gn9e3pak8fep0e84cvnpc3srt8zffqn4fs74
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOWM2Ky9IVG1VTkYxdnRp
        eWRDdk9XdThOYXFONi9ZWGcvOFVqU3hOSUdvCkJiMDErRXFaV2tRekFyK0Ryb0NN
        OGZLOTJYNUd1TFFzdEIrYVEwQW5rRkUKLS0tIEZIMThhZ1VaT0FOR3h4ejRoT0N2
        ZnZOYWZDL0ZydGg1aW02UnozNDdnU28KmNFCYcFjDggwNcsyfhFeK1eev+BZeqKY
        dTN7uzHd1+JjzV275dcwG+qkTqTkhaLXta1W0Ft2f/oOVlysQNdiFg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10yse6kg99dwtsjaq4l7umdheecwsznpk4dnu76ff5jmjuka8uv9se4ysq2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-28T19:42:24Z"
  mac: ENC[AES256_GCM,data:GJbr0Yu+fPlPDSeOe8b0GuMXjSssoto6505dYJ3SNR1hqUDBnqo1KCQOraRFtZvQDy3DPVcgo+C6gXT+Sq+FpOUXSi+uPDBE6PzfKUrcersgDB+9DgoeYMi/9j+Z+SLVm9cPg21WeQOc9Dpdcuv7mj73enh1AY9WkqJYBKmdyeA=,iv:X4IRVrKI3X0K69aPtnm4+F10UVgvyrBLEbjQrWZ6ZAU=,tag:gLccYvWS+Udiu5+DncbJNA==,type:str]
  version: 3.13.3
