server:
    pidfile: "/usr/local/unbound/iana.d/unbound.pid"
    auto-trust-anchor-file: "/usr/local/unbound/iana.d/root.key"
    include: "/usr/local/unbound/unbound-shared.conf"

remote-control:
    control-enable: yes
    control-interface: 127.0.0.1
    control-use-cert: no
