apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.homelab.wildcardCert.name }}
  namespace: traefik
spec:
  secretName: {{ .Values.homelab.wildcardCert.secretName }}
  issuerRef:
    name: {{ .Values.homelab.wildcardCert.issuerName }}
    kind: ClusterIssuer
  dnsNames:
    - "{{ printf "*.%s" .Values.homelab.baseDomain }}"
    - "{{ .Values.homelab.baseDomain }}"
