apiVersion: v1
kind: Secret
metadata:
  name: immich-postgres
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:1zRmCHmlSrBxgKvzyBTT86jvI6JwRQrN3kQRFUJvIpzrj7xWLEepeh5SNFJuiU5SjPdJaql46SneiTIi6m9kdQ==,iv:Avq58MyQlQdWh3IWedBn3IhndQv3yF0+ITFfCiKOuJM=,tag:IjBKtU9U+RVfAKsIF9gHJg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHV04wcXQ5cmd4SlJEbVMz
        dGFoeFZPL1BzbFpzdkY0dW4wa3ZuK2V6MkY4CkRtaXA5Wjlob1ljcmlRVkt1THBl
        YUxUcnpzVXU4VjlXSjBMNENLUkNsSVUKLS0tIENXM2RMM2trV0Y1Uk11bWt1L1hR
        UUJCRDRUMkRsaGR6clBIODl6WTY1R1UKOZ1ZH9ZUWOs0FXKzZAeAIfLiiDB40X3y
        AfFoifz5pjhlmQeMZ3eeldpYo6CXic7d1K7nmdeNlPXbQKEJczKOlQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n0cqvlyfca7gjasrmj4668gn9e3pak8fep0e84cvnpc3srt8zffqn4fs74
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dVJyUkwxUUZBQkdldFBP
        QjdHbDRRbHNuZUZvMUdYcW1UdUFQVTZEN0RFCnN1eEV2d0tvTmZiMnZNMGJQcEdL
        aUp4MEMrdmgybWdrb0VobU0zbW5tcnMKLS0tIEhCZExmaEJHOHc2bGFCRURSOGF5
        dUVwRUxqTVJ5eGFnc1hORmxZa2pRYlEK7smvpHyj43CgDoHAeUfZvR9F9lCbNGwv
        4pgP6iZvC/FyLevbgOogV5xzAwCMPr/dlFy9nWxiZ5UdAts9Yfhi7g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10yse6kg99dwtsjaq4l7umdheecwsznpk4dnu76ff5jmjuka8uv9se4ysq2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-02T20:34:43Z"
  mac: ENC[AES256_GCM,data:lwKy/kK1T0iBh8MzAOfr4KNLgzMIDA7i81EvZqaXBevRdBudUeY7Kt5Bayi+NWn0AHibWNFAQ5WMmyBr97tX8BK/xHToCNiIZeQX//mZVWD/v60HmyMWNpl+sH+BNkn2UI6p/WUBKrp6CTxmgq5lZylYsuCFBmpKbxHD4dd8Yeg=,iv:CqiGOUIzKOgaigjTJCZ/Bg+unsJYS0maY2dPWooSas8=,tag:Kvwu6spj4C3uE3SPTsMNrQ==,type:str]
  version: 3.13.3
