apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-telegram
  namespace: monitoring
type: Opaque
stringData:
  bot-token: ENC[AES256_GCM,data:PFw24KYok6CLWc3damy8VVW6ml0gdHFzHtCGv6pYSnUiZhMa9MQrLLjIwm9N+A==,iv:J/8Tz4B9pPGWNvky0ODr6+XTK2duRJozLBYREdZeers=,tag:NQxPlyJw0Xt4iDmWUo2hcA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1L1dxNVl3R3Q2NWdkaHRy
        QktjaHhjNTVPMG05UFNCb0o1K1hqOXJKUEFjCk8wclRwMEsvSmxFWWIvUUtteFAw
        eENZczd4ZmJpK2k1TmhGR2VQVGI5WFEKLS0tIHFWNGxjUjkzU25Pa1lBZEhCck9O
        WTZBRERYWFdkMGowRmpPQmRpWWdmeUUKtg/+tOK3NqdH75Jj1RYuWa5m09THw3f5
        epnBL5P27oup7IpzhErKzjkJjzJCDMo4d+MyY9pElPOdzdsFZfpSog==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1m8j9egmweu9c8cpz2yejsulpzy82227eceh9awergehk5pflwfsslu4nah
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T21:04:07Z"
  mac: ENC[AES256_GCM,data:ZESq5kPRffc/6jn9RMtj0JUQI9hjOeWnmQM8sS++XhsLGEzk9E2EPJW4uMdbsBHg0k9xsmsjhWhKirrpRxcj4ZYyjFbhXApI27HMgE9fgSrGZoLmR2DugFjb8UrXhudqvi1/A5YMAUp3lLMZ2HqdJQW4RAOBdIeIxXPMvSf8LRw=,iv:WyLe1o+f9FkbRqePv0InO8SVo4ZFef0D/0kzDlvZM4s=,tag:t/sh8GjXrsN7C5/EB6FTUQ==,type:str]
  version: 3.13.0
