apiVersion: v1
kind: Service
metadata:
  labels:
    app: blocky
  name: blocky
  annotations:
    metallb.io/loadBalancerIPs: 192.168.41.12
spec:
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: dns-udp
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: dns-tcp
    - name: http
      port: 4000
      protocol: TCP
      targetPort: http
  selector:
    app: blocky
  type: LoadBalancer
