repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.38.0
    hooks:
      - id: yamllint
        args: [-c, .yamllint]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        exclude: ^\.envrc$
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check --fix
        language: system
        types_or: [python, pyi]
        require_serial: true
      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: system
        types_or: [python, pyi]
        require_serial: true
      - id: alejandra
        name: alejandra
        entry: alejandra
        language: system
        types: [nix]
      - id: deadnix
        name: deadnix
        entry: deadnix
        language: system
        types: [nix]
      - id: statix
        name: statix
        entry: statix fix
        language: system
        pass_filenames: false
        types: [nix]
