apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent-pia-secret
  namespace: qbittorrent
type: Opaque
stringData:
  OPENVPN_USER: ENC[AES256_GCM,data:hmhpxF/+eJc=,iv:ptb/+hra+yoOL9KznUJQNp1XBCMr9MX2QrFAzRV1964=,tag:zw2Zd2KntQybqEzfniomZQ==,type:str]
  OPENVPN_PASSWORD: ENC[AES256_GCM,data:BfK79BcJ2pVCuviTUibuPmawgsZ02PHflk5WcT/oL6A8uI6klvtv+IOuaG04SEP0c0U=,iv:ZwWPQWafkf1m2JtIyfGsC5N9Wyusk/Dp5LWX2MNQUkM=,tag:rbm1ZfC6PqeoOlB/++arzg==,type:str]
  SERVER_REGIONS: ENC[AES256_GCM,data:XHOU7RhjVd9uSWtcudcKFTI/lPR53As=,iv:ZDHQw3GYf4q/oy2Su1EDZpD8nmI/Zf7zd2gBLsh2ymM=,tag:Ex/03L6HhUIkC7BhG1cbfA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEYVVFTlM0Nnp0amk5OGhK
        Q3drUEsyZnBkempnOHN3YlNXWTNDcEZ1ZFVrClpoR2xhaTZVUldZMEtzMk5wSC9k
        cmF1VEhBaWVCRFBDUmJuWUJCWkowS1kKLS0tIHlBb014OC93eFJtU01URzIydnN1
        UVRyTHhQdTdsUU5tYlVtVi9kUG9YWjQKnVo8mqMiQX70vxefZhuFpnFnnW/uG87O
        NRCdoAfuruAJK7vySyQcQK8Q5ytETjFBlnR6YB8ivwfggr0tyG/ujg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n0cqvlyfca7gjasrmj4668gn9e3pak8fep0e84cvnpc3srt8zffqn4fs74
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYjY5SmpTWFpqUVg3YkJN
        cG85QmNnK2VzS2k2YkpMYTRFM0dPemluSVdBCmw2N284RURiaGVoMTZPYlpUZGFt
        MHZNOHY0WjQxcTQ4TEpZamc1MEJTYUkKLS0tIHg4QU45Mnk1bjhteGtsS3JhcVlr
        enVSeFdnOE15eGMrWXlyLy9wMWl2SUEKOxlZ7tN/I2gbFUvdB3zo1ykJuPJ23Lvc
        L4sU8dmi40I0ZhUDVDzbIZW8YBTNUhOhdipIbpOu9yVI67JjiwaT+Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10yse6kg99dwtsjaq4l7umdheecwsznpk4dnu76ff5jmjuka8uv9se4ysq2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-19T11:59:42Z"
  mac: ENC[AES256_GCM,data:8+P/+AF/yY8cYlxkV+vFP19caPPEFHthiQ1uXNB6FgtW9tzXGkOWXDiKpELUUHl9MOAZJZKdzLECyJsV6WjWy6kFpWcH3mjR7EjM8HqAc/HR/C4zWRvpzl33TP/4XzeKhYQ6qkPQqJiNXLggH2oc5su2PC47KhmFbqODjpngIb4=,iv:KsGeteJt7t3Q0FK+Gw1Qbx5/L+owV8gxt3+XmGKeBlQ=,tag:o0LSGpAjxftspkrapyA4nA==,type:str]
  version: 3.13.3
