apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent-pia-secret
  namespace: qbittorrent
type: Opaque
stringData:
  OPENVPN_USER: ENC[AES256_GCM,data:hmhpxF/+eJc=,iv:ptb/+hra+yoOL9KznUJQNp1XBCMr9MX2QrFAzRV1964=,tag:zw2Zd2KntQybqEzfniomZQ==,type:str]
  OPENVPN_PASSWORD: ENC[AES256_GCM,data:BfK79BcJ2pVCuviTUibuPmawgsZ02PHflk5WcT/oL6A8uI6klvtv+IOuaG04SEP0c0U=,iv:ZwWPQWafkf1m2JtIyfGsC5N9Wyusk/Dp5LWX2MNQUkM=,tag:rbm1ZfC6PqeoOlB/++arzg==,type:str]
  SERVER_REGIONS: ENC[AES256_GCM,data:uxcKR8SKWpdtVfXze3vtNdU8E4AfEIXxjBygG5M=,iv:s0CpPaqbjsm9DLDjfsGu5nWDDHoZCqNBWGfV5wsjF3U=,tag:zkovF6f9AuP9UpOT6jKwcw==,type:str]
  MAM_ID: ENC[AES256_GCM,data:ruAAo0J/QcfNf4rCp/JsBtxMmDSsjBio0R9/a9qHS/KBkEaxd0PvrM93Z8xrHmCAoFzN+K43BhSV2GRFdzkiWS9UQXS0W+cZdQ3YT0YAl5ZfF7E/XfQyIGWm+7I+dcv1ej66e77w1+O0YT9poamFxAOfZMTfmoQP+DC/pnr4sXUHJ58EUKzvT4Fd6phbm92YHIkeRO/UVzejcBEVOsWQdDnX6xOKUGz6RYQ5I+yn5QrLEtTi/Bg0CS3TVvB2a1Sd/YSPf6FSG7A3VGnaMMP7VCiSKXybmzidf53XdcS/wQo0HY11BPOwExw9E9TWWFTC9rfz9Znnz2tN8FfxnKC4vm/yTQhNxCAJT+vu9+J1KUIoqNDksjOCpFrUlkFImY+THPwPBw==,iv:wBukxubtmmcaqgoEIh5U/8HsR7djPv5lTkMLT5mi8OA=,tag:xLmQ4ncXoZnrstFrO2VADw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEYVVFTlM0Nnp0amk5OGhK
        Q3drUEsyZnBkempnOHN3YlNXWTNDcEZ1ZFVrClpoR2xhaTZVUldZMEtzMk5wSC9k
        cmF1VEhBaWVCRFBDUmJuWUJCWkowS1kKLS0tIHlBb014OC93eFJtU01URzIydnN1
        UVRyTHhQdTdsUU5tYlVtVi9kUG9YWjQKnVo8mqMiQX70vxefZhuFpnFnnW/uG87O
        NRCdoAfuruAJK7vySyQcQK8Q5ytETjFBlnR6YB8ivwfggr0tyG/ujg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n0cqvlyfca7gjasrmj4668gn9e3pak8fep0e84cvnpc3srt8zffqn4fs74
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYjY5SmpTWFpqUVg3YkJN
        cG85QmNnK2VzS2k2YkpMYTRFM0dPemluSVdBCmw2N284RURiaGVoMTZPYlpUZGFt
        MHZNOHY0WjQxcTQ4TEpZamc1MEJTYUkKLS0tIHg4QU45Mnk1bjhteGtsS3JhcVlr
        enVSeFdnOE15eGMrWXlyLy9wMWl2SUEKOxlZ7tN/I2gbFUvdB3zo1ykJuPJ23Lvc
        L4sU8dmi40I0ZhUDVDzbIZW8YBTNUhOhdipIbpOu9yVI67JjiwaT+Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10yse6kg99dwtsjaq4l7umdheecwsznpk4dnu76ff5jmjuka8uv9se4ysq2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-22T21:42:49Z"
  mac: ENC[AES256_GCM,data:kp+MA9IuceKiS+NpmdjqG4aOcBU5u3UD7ADtnA1tChcCnpX+sTO8TVLIgsKffxZKpHX0hVySRRFOaP4ujJN+MOFbXNJI8JkxHDjp+E4ZkUVDvJjL7UY1DDLjranygt8oGMqye2d1u10pbWK8H990otviJVvKfLhYpaBr6EGZr4k=,iv:dnuMhDi1t9+PYAeN4cA+QvovCA6gXhLO0CFOUvFH2G0=,tag:AHJsw8t4pqkOqtv9LMZOGw==,type:str]
  version: 3.13.3
