apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent-pia-secret
  namespace: qbittorrent
type: Opaque
stringData:
  OPENVPN_USER: ENC[AES256_GCM,data:fJ1AbE4KVyQ=,iv:r6kCqAPFXa/mbJA+jZZw8glef5x4WpwCBYlO5JP6uUI=,tag:4jFjFTumicotW3zxSPJl1Q==,type:str]
  OPENVPN_PASSWORD: ENC[AES256_GCM,data:AWCrZsTNejs0OAGVh+JztkqQ7x7amEjnFJuNOYQX5g==,iv:GyLnc1qqWNUIJiQwfl6vg6qfSAGMJRK3y/BgWvBDrXk=,tag:+h3ML2O5A0wc2t4a1lGs2w==,type:str]
  SERVER_REGIONS: ENC[AES256_GCM,data:uxcKR8SKWpdtVfXze3vtNdU8E4AfEIXxjBygG5M=,iv:s0CpPaqbjsm9DLDjfsGu5nWDDHoZCqNBWGfV5wsjF3U=,tag:zkovF6f9AuP9UpOT6jKwcw==,type:str]
  MAM_ID: ENC[AES256_GCM,data:11EXsirWWtSkExvexQZe2DYHOQdjMAnjT5OJLFiVHCs7CPWE9ObiSfbPsQR7kF42qEaP60uuCgjkAdeFrjLpsZDd2OAV2e/gWhZKocsVEmZeqdUcDSQ1eJ3nmcN02AyMgTUJFaF4F5OHXfu8pU42c9w/yRfI/j2ffg+lONXGk7BOZ1VeRHVDox9wRdGyTn8EaDxStIht0LcVA1pAgyccstx58JFtuX9ztGdDPLOV1aT0yK2br+fG6lXC+odFVxV3QnpCCEgUqmoi1mEDpGxh7yPsZK9HMwgNjtDmeDv1kR74PDD5WkfOUOPnVmMvp1YJ4Ir5Ldt63vfalkY5tf47EFpcWFCDoBukK2qI9RSh1tnMwycUdhlhqWTf90znBq7TU6CyLA==,iv:td/mi8uGOfunRt4rjdGkvsRwjO+l17V+hm3XNSfvB9g=,tag:edwulUijED3LwmBhABD83w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEYVVFTlM0Nnp0amk5OGhK
        Q3drUEsyZnBkempnOHN3YlNXWTNDcEZ1ZFVrClpoR2xhaTZVUldZMEtzMk5wSC9k
        cmF1VEhBaWVCRFBDUmJuWUJCWkowS1kKLS0tIHlBb014OC93eFJtU01URzIydnN1
        UVRyTHhQdTdsUU5tYlVtVi9kUG9YWjQKnVo8mqMiQX70vxefZhuFpnFnnW/uG87O
        NRCdoAfuruAJK7vySyQcQK8Q5ytETjFBlnR6YB8ivwfggr0tyG/ujg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n0cqvlyfca7gjasrmj4668gn9e3pak8fep0e84cvnpc3srt8zffqn4fs74
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYjY5SmpTWFpqUVg3YkJN
        cG85QmNnK2VzS2k2YkpMYTRFM0dPemluSVdBCmw2N284RURiaGVoMTZPYlpUZGFt
        MHZNOHY0WjQxcTQ4TEpZamc1MEJTYUkKLS0tIHg4QU45Mnk1bjhteGtsS3JhcVlr
        enVSeFdnOE15eGMrWXlyLy9wMWl2SUEKOxlZ7tN/I2gbFUvdB3zo1ykJuPJ23Lvc
        L4sU8dmi40I0ZhUDVDzbIZW8YBTNUhOhdipIbpOu9yVI67JjiwaT+Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10yse6kg99dwtsjaq4l7umdheecwsznpk4dnu76ff5jmjuka8uv9se4ysq2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-23T23:46:45Z"
  mac: ENC[AES256_GCM,data:exR62Tpn6Nl86/EA9WIDZQ5tQII6ruY0r3DIdH+ILEKDhgWZAnqfSPiSKs26kt8JEPCPqWHZ7LNHsgK7VSF6zzYAfKjl9LDdCoRSEtYw7vf1MpPPuBLS7b5h4pawMZdCgu39QykU1C0EgW0jM3Zh/zY2uWaUSVcv6hiShnvYiCc=,iv:S2XF+5rAmYsvxN70rWePDemXKBoQO/FY1hYm4POFFZY=,tag:eWmsSE5hZ650mx3dBChsgw==,type:str]
  version: 3.13.3
