apiVersion: v2
name: monitoring-vmalert
description: VictoriaMetrics alerting rules for monitoring
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: victoria-metrics-alert
    version: 0.47.0
    repository: https://victoriametrics.github.io/helm-charts
