apiVersion: v1
kind: Secret
metadata:
  name: audiomuse-postgres
  namespace: postgres
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:Tbl+rtixaes8,iv:3AoBFLJgE41il6dTWu5uwgLXs1Snvj8U5BVqdMabL7A=,tag:CwaIpSoYjX8qItX1rF/cVA==,type:str]
  password: ENC[AES256_GCM,data:7gRpV13kOCrvIkI+C/Ki/0+2yJFk5jJ9cdnQzFryG72JPMgPkpUETjq1rSOw6YwP0Qg=,iv:MqYiGOQ4MA2y6W8yq0ansBx6bmpGu0dh3Qv3VkDw9ws=,tag:VLpE6eNiK/osJW63guj4OA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOVcxMEwrek1mTWZQcG8r
        azFCV01qQm5zZTkxUEsweWZkRFRmTks1enlRCm1Ed1cyZHREVWFLK21MVHJ4M2tx
        RVVLM3lUQ1Z0OUREczFDcFZoVGo2cEUKLS0tIFVqOUN4dk5aT2o3Mm9mRmlPWENZ
        SS95dTVnOW5ReDg3b0EvYVYvYUxmWlUKBEqDX7i8XD+ExoIOb5qhxHy3uHlpkbKM
        T80TTgFbkcif3kHsyliuCTPAvsNhhCofSmc6pu0LsM/UKB9J+uSMyA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n0cqvlyfca7gjasrmj4668gn9e3pak8fep0e84cvnpc3srt8zffqn4fs74
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0S1h3SkZhZ0Zob24ydnlz
        ZDVaYVBQb2dJNlY3bm8ydUE2OHFTNDVESjNBCjhjcEpjSlN3OXVmZEk5NDZXQVF2
        dG0zYk9aa2l6YTRIVDZ0NGxRTm5lV3MKLS0tIENpOEVxRFVCZjErMUptY3lJVWk5
        RXh4cUhlcXNTWHEwSEdKUlp0UFVZMFkKyGowBM31AanQ93iq+oMlxRiuNuSb6by8
        Jn5muqhWy1RVIuVmbRlnFTdG+tNSqGDCuIkoue9IzORBKmXtmT6sgQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10yse6kg99dwtsjaq4l7umdheecwsznpk4dnu76ff5jmjuka8uv9se4ysq2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-09T20:25:31Z"
  mac: ENC[AES256_GCM,data:nPbz1xijeQruqdNMKFQ5FzEQ01r7NC5PYnf7hOdrYsVKmqEJ+kcA8u4TzTnsPDG/NCMCd7WRYLW2h0BCK4oizRyJuGMyILZ4ArfsP6W8s7QIaZJjy+CFockrrQMZPSNgJzH+ueFVDHhLumKWGNiaocS+64sSp71++tQFPmkfeF8=,iv:jGhrKXiJQNDh7H4kFzJgEjBbjcOmFTutoPwcSltWz+E=,tag:oZ0Ah1GYIO16PF5aYzJxjg==,type:str]
  version: 3.13.3
