apiVersion: v1
kind: Secret
metadata:
  name: immich-postgres
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:KDWty/cm,iv:SBaXk4Ld1b6ektnYDNEtV28fN1xEj1WA6jmS5XPkbyk=,tag:5g2Z3TzzxS4xSUBmnG5E4Q==,type:str]
  password: ENC[AES256_GCM,data:wprE4Fu5mcBHndHVCMAqIq3Rd/65Ge+LVRjoow/EhxtcCNXyD4/eLV8rOhaZ98+NbNXzc49Qh262rs3PDpYaLA==,iv:yVyrVNOph5adsCEPo6ORgWZxTOvjfj3t53s0LxtYNQs=,tag:2PcSxXjwQOOQ//yyZvNxtw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZ0J6bTZ6VFBzTCtNWkI3
        aVlWWGd1T2FHTDljV1JlK08ybGZUcWM1QVJRCnVuNXJzZlRRbE5XZVlOeVljaEhn
        VTFSaXJNSzI3N0hENXFySmorUkJpREUKLS0tIDU5Mzd6VU00UllLdE5GSDVUSGJz
        NWFseU52RFI3S1JtekxBc0Q1UTFXek0KRW5aPws7pJUME7RGnGUodzFHwGgqb5z+
        2Cui2hIxtYhcAtu0oBeiuP7LKDXuzcPTu8mATIKfVXOSVp86sMX9Uw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n0cqvlyfca7gjasrmj4668gn9e3pak8fep0e84cvnpc3srt8zffqn4fs74
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZDkwSTBDU1dxRGhYZDcy
        a1FZNEVhNnJFMnZTV3RZMmd6b3JKRGlrNlV3CnJjU2xpZlNnMmNpcXI1Uk1sRnZI
        QWQydHdUYnhRQTJxTzJzbUxsQkxOUEEKLS0tIDJDekJDY0gzdTZhZVdxNldiNXpO
        VE55TmRDa255K0NVT0hQQzZzc20wTkUKmZdWC3+ZbSLu/e91wbIHEd0P+N1a/Q4B
        gd8qMkNoiCnxjXl81w/6/TmJn3Fj/Y4+QlhVmD+h72JiNoCUeMUfmg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10yse6kg99dwtsjaq4l7umdheecwsznpk4dnu76ff5jmjuka8uv9se4ysq2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-03T17:19:52Z"
  mac: ENC[AES256_GCM,data:oQdNQ2wu2FuB91oatiiJu5Sl/s9qVTsSnl2Rikat58drgNIiwNljvrlZQaS77kAcjF1kggOG2CJdau8s2GS7X8nCJIQjmRKMBvYdvZVU0to+hYioABQg6Jq7iwSAulsmYwiqUwQzQgIQQkza/clP/iiE1PPrXd1zpqH9x38GiI4=,iv:M7so07Z91lkuC02Wzq9odNwEWtlVuPQLmATVG1lo5AI=,tag:Cd8sVPJdOG5/8ozuDrXcGw==,type:str]
  version: 3.13.3
