apiVersion: v1
kind: Secret
metadata:
  name: immich-postgres
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:B9AnajDj,iv:QnnvlCOGSGvfJLZ1g2CElRUNZQoltE5oU2OTOeA6lPQ=,tag:G51yzIQVVbSwOyVzMPTrAw==,type:str]
  password: ENC[AES256_GCM,data:ovSJRV/7zeH9MqhpqMOb/jUndZq0yAR6iExtjuKVqXRI8cZr9wYOr0uKuYi5Lh/8ISqACfqkavl+C0qUQ1eWuw==,iv:x5x6M8udJz69qThtV50aw8PBGpxYh6rZDGq1OYiXNqQ=,tag:K3xcTBdmcoikNtinHez6qw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdktzZ1FFdWFaOXdmWFhn
        ckpFa1phWlJka3BhOVBxOUNHSmZuT2hwVWpnCmtnWW9zS1JCbi9JZDNPcm1Dd2lM
        b3d2VkRkMUl0R3FXNkQralhuTVlMaUkKLS0tIHpya2xMbjE1ZDFmeS9WaWgwS1ZW
        T2tZL2FSUkcvVmlpM1o0VXF0VThRcDgKy1a/Ol6zUNTrIvj/BVcDps44q8PF+5Qv
        bx+Owqd370YOE60BgHxt5cqDct/9CyGMVUixLAsasfjZDL7o03AO6A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n0cqvlyfca7gjasrmj4668gn9e3pak8fep0e84cvnpc3srt8zffqn4fs74
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITnZOakJDbHhWbjlWZ1R2
        di9kZzFCQ2ZOZm5yMWVjSitCcjhpR3V0VjFZCjUzdXpyRUlRdlpIL1dZdXNFL3lw
        b2doS0VtcU5QY3l0Z2lYcHc4QmVxQ2MKLS0tIGRxQkFsVjdoN1hTdzY1Vnp1SHVo
        bXVGYU9oOHZDMCsvQVRHd1F5cXdxbGcK0EeWSaMa7TYkpw65aQTqxnScpmv3z+Li
        4QQU+zP8ViwEYBN7geDKV41SWuSq4CKR8KYMsrGQmxx0YscmTxnhAg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10yse6kg99dwtsjaq4l7umdheecwsznpk4dnu76ff5jmjuka8uv9se4ysq2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-02T20:35:44Z"
  mac: ENC[AES256_GCM,data:6RkClrmZKlFAXWAIQlzZ7FcbwhDUZRXnQ5E6ccVhAPbc7acKOy7IrEdVRt3O50UUR4FBnJTVO+u1ntyM0Gyrt9PQ2HwNwRlQTCexCBm8E4zfrBISeffyPUoOKvCAMl+qMDeC3DzFNyKdB+9sDcKIy/S3AoyN6ECJUNnWRdMghPc=,iv:Eooz8420AfUw8VzCtxxGatqqDMokqEq1Qk+N4vTyh+c=,tag:FYt9Ru6uekOLI8eUjL+1ng==,type:str]
  version: 3.13.3
