apiVersion: v1
kind: Secret
metadata:
  name: postgres-backup-s3
  namespace: postgres
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:R3gLjF6KBCJjxMqO5V0T1Xm888J5sMwpPPg=,iv:HUvnADf9DhZQkmOxyflZR7KGb/MnAqQL2Uv6Zb/O+Aw=,tag:9df7BahkwRmgkLpWeYID1Q==,type:str]
  SECRET_ACCESS_KEY: ENC[AES256_GCM,data:8/aUpPReK/eZlLiuXUbO4e/OQSIZSQbFXZ6SAtR/qH+Z3ixId7Dmr28zyUyRgKfwgZrNgGRTr0Z4cdrzJMDPyA==,iv:gGlN+61JYQ83HSTzrPaEXCXhAmMqdLfnYe/kl6yLjF4=,tag:ZpuILdrM9mKxVyAYk4YmJQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVa29wbGZNSjArSXJsVTlM
        ZzAwcjVRcTZEcjFjMVpQZUVMbUdJaDhDbFFJCkV1QzhYTENsZGtFdUkrMGxyR3h0
        ZldEQm5FZVk2cGtXYzZ6MXZ1aXd5bDAKLS0tIGhHcHJqb2p2TmFZVU5pVWVvQ2w0
        V2gwMml1aDNmeU9DWmZIVi9ESGlESm8KHFZHvPVelNiRxqmFLihXegqhmM34IiOs
        M7cQyqZWXLBzxa6o6EPoCksGsz0pix/0PpdNkEU29TxSQk8Ddq+DEA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n0cqvlyfca7gjasrmj4668gn9e3pak8fep0e84cvnpc3srt8zffqn4fs74
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwVGRUZjRwTEdRTC9sS1Y4
        OWNuajBNa3RJTDUzVjVwUzBTbitsZVRvREhZCi95RkN1dlZIWGNHNkdSZTN0bmZX
        VmNGSGFybWtXR3R4TEIvRE9MQ1dwTFUKLS0tIFFTRS9qZFBMYk51aERUQlJJc1dv
        Qi9MVHZlY0tKQVJYZzkvSHFZQXZodGMKU0wDKOIOnFZqyx4WDcETPyYYlwSpBLzd
        3veYg6JQV1hvdFN3PTaAzI0LKoCwGLnkUnyDSA3BZLYqHMu4OUXn8A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10yse6kg99dwtsjaq4l7umdheecwsznpk4dnu76ff5jmjuka8uv9se4ysq2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-28T01:50:27Z"
  mac: ENC[AES256_GCM,data:805jJOkEubMXU0jb9Sk2MfY+m4lS9S/GdhwFaqQcFDp7BhKKuVoHLYEJYqdVqfCcCLXKUQF/8o6r064Uta2M2YF1ui7lh9zY530F98WKAKecpklviQAVKMKDNEj8xGLbCCrTkFRdXk/6ONA2h83IyvubflhuS4G/pG4WyagQRuA=,iv:bECfQvXFNC59cHAPs39X/ayMeoWsI3uShZV1WJyfbSc=,tag:Rjab2HPPxAwHOw9LC8LINQ==,type:str]
  version: 3.13.3
