# Swap configuration for b360
zvol_swap_enabled: false
zvol_swap_dataset: "rpool/swap"
zvol_swap_size: "8G"
zvol_swap_priority: 25

zram_swap_enabled: true
zram_swap_algorithm: "lz4"
zram_swap_percent: 50
zram_swap_priority: 100

# Power management configuration
power_management_enabled: true
power_profile_default: "turbo"
power_profiles:
  powersave:
    governor: "powersave"
    epp: "balance_power"
    pl1: "35000000"
    pl2: "65000000"
    aspm: "powersave"
  turbo:
    governor: "performance"
    epp: "performance"
    pl1: "65000000"
    pl2: "65000000"
    aspm: "default"
