longhorn:
  persistence:
    defaultClass: true
    defaultClassReplicaCount: 1
    reclaimPolicy: Retain

  preUpgradeChecker:
    jobEnabled: false

  defaultSettings:
    createDefaultDiskLabeledNodes: true
    # kubectl label node NODE_NAME node.longhorn.io/create-default-disk=true

  ingress:
    enabled: false
