longhorn:
  persistence:
    defaultClass: true
    defaultClassReplicaCount: 3
    reclaimPolicy: Delete
  
  preUpgradeChecker:
    jobEnabled: false

  defaultSettings:
    createDefaultDiskLabeledNodes: true

  ingress:
    enabled: false