---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pve-exporter-secret
  namespace: monitoring
spec:
  encryptedData:
    pve.yml: AgBH80E4DsFLS95Rr8ebKzycEMRzcxnmQXliVRsaXs2DS6RdzZ5jdjnMdzlJLug+vIVCtjE+wpu1iC6657Io886kLEXg/sdlFegf7HRv01vV76oQIb2+HWnQiPkQi5tx3AN/Uo/xoAd8gzp4crb9xGY8J94sg7+2o67HZhigdJXYma9g9Yvh73An0edtsVeooIFQ+N8n6ddwhWUrY4vdDqkqT2KYLN5fssOiNsCXqh9m1NM04TwHJ8cz6M2h2gKEgxAd9QhY0bGbDmCCTvMAveGZ4IHE0/r7Hb4lqRHwR9OrKe38y8rVyOHA8fmCfSyjZ/1IPJGtGyBafYbBFjuS4McuPpTDJlIaEdpBATA3eXDacJtwu25EBhD+NjMcqf2XgeHzj+PA+7yPpKIpRJo0E14w36XWXTusEUxkrsOdmjFblq5AMUoXEF3rWHDpGkJnWKgkN5eytmvOj2iA1fNeoFSXhxXtOH0E4hBlKFPHBrLJ9xjwWn0Drwow+0GN8fNCq/ZTDbVc+EMrtWQbc6HXPov8+XhLr+NRt88KiqNClpmlYEVL4xC0p7hSrk2naVDK0Ifn7XX7eYCSDMzaX6HCtFJymex2+hI6UGoJvKxJJTNrZMnrxLjhRWnpII7sr+XDLEuJZtot++WiVZi/2Ocsj4ozfhSrdIGFexmg+gewHnQ7iFwCICzIixVEAvoqFDYWtZtbpD3ohQGQSOCrQAX/PhUuHyHi2sJl1/eZIsPDOPZy6CMVj/hUMHvgqyJGsj6Gd6CddsMw0fFyw5zYHh4oh1WmpGWYwLLPGayevU9tZDs7Zjj+VqgUZ4RHAVnSlcIC7DfABhsd0j/ooQRgeUzgV+QBohXh4nanZQ47P+FrKCzymcEnLO8YVWzQk8hNvgsU/2c= # gitleaks: allow
  template:
    metadata:
      name: pve-exporter-secret
      namespace: monitoring
