apiVersion: v1
kind: Service
metadata:
  name: unbound-service
  namespace: unbound
  annotations:
    lbipam.cilium.io/ips: 192.168.41.11
spec:
  selector:
    app: unbound
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 5353
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 5353
    - name: metrics
      protocol: TCP
      port: 9167
      targetPort: 9167
