apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphite-exporter
  namespace: monitoring
  labels:
    app: graphite-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphite-exporter
  template:
    metadata:
      labels:
        app: graphite-exporter
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: graphite-exporter
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          image: prom/graphite-exporter:v0.16.0@sha256:e54bca6645ea8a9e8c52312a8540de98ad08819d38476c021d77a0eae75bc797
          args:
            - "--graphite.listen-address=:9109"
            - "--web.listen-address=:9108"
          ports:
            - containerPort: 9108
              name: metrics
            - containerPort: 9109
              name: graphite-tcp
              protocol: TCP
            - containerPort: 9109
              name: graphite-udp
              protocol: UDP
          livenessProbe:
            httpGet:
              path: /
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 32Mi
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
