# kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/${version}/config/manifests/metallb-native.yaml

# sudo sysctl -w net.ipv4.conf.all.send_redirects=0
# sudo sysctl -w net.ipv4.conf.default.send_redirects=0
# sudo sysctl -w net.ipv4.conf.ens18.send_redirects=0

apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.20.105/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-l2
  namespace: metallb-system
spec:
  ipAddressPools:
  - default-pool
