homelab:
  metallb:
    myASN: 65001
    peerAddress: 192.168.20.1
    addressPool:
      - 192.168.41.10-192.168.41.250

metallb:
  prometheus:
    serviceMonitor:
      enabled: false
    podMonitor:
      enabled: false
  frr-k8s:
    prometheus:
      serviceMonitor:
        enabled: false
