---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: searxng-secret
  namespace: searxng
spec:
  encryptedData:
    secret_key: AgBMVgI9jnYWddNjDFG4vwzKXO7pnLZg7tHqNZ60ybqnduCY/nSylcQvZwwPWKTC3UDsopGyPm+9q5F0ORFqq8+jPr9khyywVhreTGHrUWm0ARcJj9PqUAwpKMFzc8aMxwQYf+RneGL08I/6XavvMIq/Qk8M0uyo0JdT4DcbI+CWGQp26eoPnq4V67tiQw6mAR8ZQh9mnnkRFgf+m/aAOr486pNmflmW+NfEtLnvGwZGTuPDghjKwhSjwQ9/kuhYBcBcOKTUqS1iRXyhZhfB+B8+FWZiITLbVHMq8jHiqlkpHc0E7rr6hVyhIgB5yGuqfGroJq48XkW26l7Ba1GC8NAQJiRJetu8G9jZH9CLT1/gLmAlW5ZExMaIasL+NNsMFAz1uxwD93IgldihnRQONMPnqgwSlFh00l3mmm7L/CKFxba3I3yuCWQs81Y7JT6WDDVB1BbtjL9BZeqcZueb01I4V2rBhO7iLxbZrkpqQqV6NJOMy8Gp7Ac3kRl9lX1CQ7PWpBs6aE9UhbNoX0ZRhX1DiExngIHSp5aVQkHpAAjKewtY/rcz77CDurukLo0oxJmQzOrFgyGr9k7xy+PMpkmZAKPowuiO0A+viIfAQG2lRBEiEERyaCb4g7/2Ue68XFn8QkBovpR6zf0hdsCjxc6CbERPlKmJKm+EAaAJIKx1z5YSmiXtl+KEdRz+W7c3XkAWDtYs1bmjG6JNNmko5Bgd05ZMdLglBWhTdDKOjlERMUA0WCReD/Mjm5jCmrGiJ7XkuAGHh+3Lr8Bt4gLZpCMQ
  template:
    metadata:
      name: searxng-secret
      namespace: searxng
