apiVersion: v1
kind: Secret
metadata:
  name: searxng-secret
  namespace: searxng
type: Opaque
stringData:
  secret_key: ENC[AES256_GCM,data:d+sVgNi2rMJvaRhox1u2rMHd0vsvazUKSIGNmlJIxgGIIO9vhKmVYVbTK/4kBA+8LtCHWfG4Pp3gnIVoW21yRg==,iv:nQ16A5r3tX+B+Eh+umpXi32LyPcm5O9H+7RG8hdhQnY=,tag:vDlTHUQxNNl3QibD7Q9/Pg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZkFtbEIyL1YySWE1UjRo
        dEJFaHUzTkg4bStPWVdCN1V4dTZWWmdIWXdVCldSbFp6L0pTZHZnZHhaYStVS3N6
        YkVjZDhjd2RMR25ialBUa2IrTTNTdDAKLS0tIDZmNENKSnhLT2xIcFUwM2tONnNK
        RVRrMk9ZNkwzdXpIbFVXVkN3VFJoOTQK3mnNeKafXToA59a4mdFGPi2CEDx3Wu4g
        YsOs4KqwOivSUt0s8hgxMQ6PyHmpbnDC0TvibYEOLqUuxCqMvMzi8w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1m8j9egmweu9c8cpz2yejsulpzy82227eceh9awergehk5pflwfsslu4nah
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T21:54:52Z"
  mac: ENC[AES256_GCM,data:u46N8ZYW7f7NcZaRkjgf9ZNDybo5wratNbuC1ApacTzjjAsIPkkZ+QgTaIh/Dg/Vy4TAOsVMwZtTn818hsz9RTR1oPJOjDt/o4E9mVMz/J5zu8Qr6YQebaQE7YBtlYvZlsS1wMU8eJ0recxFtCqEl3u4cT7rnn2DkxK60gjsmMo=,iv:+1D+xsB3vVmPvOMvvt+n3LNv7dJZSbhsuE9uJ/OIFFM=,tag:8B8C3m0HsCN2ogcMCCEOxw==,type:str]
  version: 3.13.0
