apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opodsync-pvc
  namespace: opodsync
spec:
  resources:
    requests:
      storage: 256Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
