---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: duckdns-secret
  namespace: cert-manager
spec:
  encryptedData:
    token: AgAunxTtzwDQlECOrA3OQwLj04MOZoX1a5G5sRZDfYoEXM0RDvrWX5edJ++gsxmglKI6wzYeUy6wKe38iOKSEmX/ottSx4G0QpTJITPMA/jEOpVCY58eCbbyisBqi5Pw7Slg7pcJlNRvaNEdBWTNyhYRKr9qH1XPCp7K0f7KpdRQOG/h4StzcrWzRws5vQpaikFJrilRMgkaKZvY74ja6ciXFqUzONcGsFth/lNNhgD3xp9Juz8QdgPPB651mTSQmMP4LlcJQB1jDtjIZ3CiFpKqBcAfGBOn9LDhz+X/nBu4lINliDTgTj6O2gg90Omfy+I36X+bNhJz5x3lar9I/wXxqx11e5kcGe0ZcQtJ6mwKocMppnWqFeSM+Vi6o2y7gujCmJoMC3ZFgF1D9GkkYeYQF5fJgteKWS4QblSKARUQEgxfh3l0qTB+dOt9aXey1e/XLtByfy9YWKT3Wm9ie2J1+l21rZ/d4fBcrkkrlCSavfyeJ9lSDCkXTO2c2tUdS8+6rMadwfpiugyFHAcUQz92oCk6NAtUbFt4lCmVB8FYwJ22FIOhSP9m9IB7L1hryAmCbtRN0skUsz/flNKQ+cSrTxwY56Xyx48/tE2dDnsXYODBYcJDYyda2hJWpH37a95hTbIK6VyBHxt/wZOZT36M4mlE9x+uPOPnPeAsSuUv5vPCaxHf3SjrCRxUnajLMxOQEkZtSEyzA3PrkdQEjBOK7YvDx/8JfhSu6LxBzuNTGlTc7Uw=
  template:
    metadata:
      name: duckdns-secret
      namespace: cert-manager
