---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: duckdns-secret
  namespace: cert-manager
spec:
  encryptedData:
    token: AgBQ5A6wJbb4D+6kRLXD3aqzx9XgQ7mD/aVNnrLW4umWJ613heweCHWou3JrZ0ukl+j5YX2ZEG47MFYaUuaSvCichF9iZhpDtXiQE3P71GWKuIJ5aCPqwmPYg+9n8QS7vjBKyQEIa33cO5ghvnnMX6E4R20RW9ZOWqUXft0R9SB9KH7vz/ujGVSVO6INbBa/58tDS8M8x5TTurdgvc13OIZ7jc4ek6eFlREcuVBWYm67/9lM5tAwEX1VMgT7ooVPyc5VYmxNdmuqtlZmLSA9K5QeuiamS3wYb+lviVb5iGzxrpaTEA/qm7SkyAhA8hdlnO016/IDU7ce7yvZtrgkj+s3xO5P7sNk/TDnc0fUs3hT61nhIg2fJsWUfm7wfVeGfqzZyXhjYLA4v363uHI/bB2fRsMfB1GwQe18QYHUYxtBMULgZPbthgOSkDtK94FPG/JnfOlWDN4m5TvaMua6pi7ztIBLIcgLpA9r7gLOUyNr1LkjXq7DGsQ9DG7JNrTSPgMyThHfFgaPEw8Q1W3y0m7CMM1T8Lqc/ydYxn9QfO3Ohs1xuZT92HCKrnvDXyCmtmgV8qdDnGv1jjZFfjEitvl5UcIatapcjUQwISI4zVKE+f5sRo4wlhVtx6gLD433YCYE4IlB3yNcuGFMHKf/gVKJR6/rBeqSk6lLX0NHQNnjJ71gBm5iyjGq7I+lu54YrsI=
  template:
    metadata:
      name: duckdns-secret
      namespace: cert-manager
