cert-manager-duckdns-webhook:
  groupName: cert-manager.webhook.duckdns.org

  certManager:
    namespace: cert-manager
    serviceAccountName: cert-manager

  token:
    existingSecretName: duckdns-secret

  securityContext:
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
