apiVersion: v1
kind: Secret
metadata:
  name: longhorn-auth-secret
  namespace: longhorn-system
type: Opaque
stringData:
  users: ENC[AES256_GCM,data:zc3k2AyQuUcFSbTkfjdisjvVX7BYOR0HbIaGDUJ0JjjMKzHwMZqnVEUjbQ==,iv:Gw2/C/hhMLVuGk3B57PGS3/aZ/O+i9BZqkYSzRMF6pw=,tag:viS7+PYtwekGCPK5fxXXZA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVlBMa0F1djAyRXVIQ1hV
        TDJMNytvYVgvcTVhQXZxZC9JUGoya0JxRDJnCnNnazkwamdBNUJPTkthczFpY2w5
        Z3NxaWh2ZHhBVFQ0RE9tV2hlaXRHMFEKLS0tIFFQWUZBb1Y1WEVLV3FsZkdyNVJX
        YUpoUlhqSnd6RmJrT2w4UDlNNzg2ajQKA028N5sbeg9XEjM78Z4HrtCvdvPd5JuM
        ZEs5Yg0xum9vPqp7S+u1z+Ac5DGqzxPqrnOwUaB92D1eESC0QFdTPg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1m8j9egmweu9c8cpz2yejsulpzy82227eceh9awergehk5pflwfsslu4nah
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T20:55:28Z"
  mac: ENC[AES256_GCM,data:in5CFYCw2Qk4zHm1QvmUV6ntRZgRQogwzjQOhLAd6u458AaAmwgUmumUSOvFRbhEQENadQt0JPCHmkY/ym5trN4xVpRdSdUUuu8f9J4JvphaTRfmtL7hi7nkuxmBjO+lGtv6NvxR5yhs338XNtpMbUtdBgVB7FNW2MPwlZrgCUQ=,iv:loFfgjVlawgr+R/KOWSpyTwv2P1Vy7DvjaIdiNhHAU8=,tag:i+lQ32WJeaeiRJJ6F8YPvQ==,type:str]
  version: 3.13.0
