apiVersion: v2
name: traefik-wrapper
description: Wrapper chart for Traefik Proxy
type: application
version: 1.0.0
appVersion: "3.6.10"
dependencies:
  - name: traefik
    version: 41.0.0
    repository: https://traefik.github.io/charts
