homelab:
  baseDomain: lab.hddq.org
  wildcardCert:
    name: lab-hddq-wildcard
    secretName: lab-hddq-wildcard-tls
    issuerName: cloudflare-letsencrypt-prod

traefik:
  service:
    annotations:
      metallb.io/loadBalancerIPs: "192.168.41.10"
