clusterIssuer:
  name: cloudflare-letsencrypt-prod
  email: example@gmail.com
  server: https://acme-v02.api.letsencrypt.org/directory
  privateKeySecretName: letsencrypt-prod-account-key
  solver:
    cloudflare:
      apiTokenSecretName: cloudflare-api-token
      apiTokenSecretKey: api-token
