apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: playground
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:59oe1KeXiqY=,iv:yXfuyysrV8RdJ+d3Ym9ZXNVWXu6aYDXVb62ba33Ea84=,tag:bpBhZc+onM9bSzaf3aSYtA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RC85QTI2bTJBR0NHUldx
        dHUrN1oyV1pFZTBSVVdsWjEzM0EvcFpWOFNVCmhQa3VMaGtONVp6NmhYSURKbDlX
        aGRJbkFuZk9sOFFwajFuR1RWVVlxRnMKLS0tIGJvd3JtVEdFalhDcU1Ka2ExR3dM
        RmxGQVpmVy9JeEhNdEUrdHFLZjdkQkUKFeiEWawCPFkTDMSyY+VFMAiHmPC3FaLD
        Oa7r8Al4+vNY4evpOGI0RE/Ok3zjM2OU788dS2rQs5/YDLZcdPpgYA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n0cqvlyfca7gjasrmj4668gn9e3pak8fep0e84cvnpc3srt8zffqn4fs74
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRC9iK3U4dEkvNmpqLzZl
        d25JNUVmTVF0WDRwT1hSOHVpdTU2ekhYWVRnCktCcElhYTZuNnl6dTU0Y3JmZFZO
        MStiVVFNNjdOMjVuNEY1TVVxQXBNZFkKLS0tIHR3TThBWTEwZ203bGpNV1plTW5H
        cTd3MUZlU1psYUs4cENWTEtwY09NbmsKhw6zKDBkV0O/35gs47CWFZdcRPysIus0
        m5scBr3UdYn4wSomFBI9rNjSQuY9mbIoLAzUX1Xg3jJVexZ5YHqn+w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10yse6kg99dwtsjaq4l7umdheecwsznpk4dnu76ff5jmjuka8uv9se4ysq2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T21:51:08Z"
  mac: ENC[AES256_GCM,data:Vfm13nsumEptG8rw5i5L+TKiUvBA1xl9df5sCAZVGrBLJz2uMEtA+ZMRz8zjXwP8JjKfh7HleiXstc1iZlKxC3Ougzu53kFOkubKhigdCK/CUWAIQZOrkPZnSqomIo9XfDLq3fToftjBapZur983+c6kyBqcfqTy3FVZ26FE2wE=,iv:00Qbw4nLASBnDh4hu5wLC/INpjykUEXM8uRTUSaqsMY=,tag:D3DXlVNw8OatMt+Ca9CKCA==,type:str]
  version: 3.13.0
