apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: playground
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:59oe1KeXiqY=,iv:yXfuyysrV8RdJ+d3Ym9ZXNVWXu6aYDXVb62ba33Ea84=,tag:bpBhZc+onM9bSzaf3aSYtA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MStMVWx0TTI0eUwxcy9t
        elJ3UXBtaGRmYlZ3YUdzajJ5UXErWU5YOUZZClpjVGdpZThYelBsZWVUTDMrZkNt
        NSs1VzdablhFUkhxcGVUS1dUd3hrY3cKLS0tIHlGQ2ttckE4WXhXUFJnOTRvNk1m
        a3l5TmFUNENkMUVkaUVDSWFySC9FYWcKXOv2n6ojAcFUj7zpSF0rPkS5Yzo0FqC4
        ZzbI9lREtzY50qKEd2a0x4qKt0wFo1KNziDWft2RYDweZGWNbfXDaQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1m8j9egmweu9c8cpz2yejsulpzy82227eceh9awergehk5pflwfsslu4nah
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T21:51:08Z"
  mac: ENC[AES256_GCM,data:Vfm13nsumEptG8rw5i5L+TKiUvBA1xl9df5sCAZVGrBLJz2uMEtA+ZMRz8zjXwP8JjKfh7HleiXstc1iZlKxC3Ougzu53kFOkubKhigdCK/CUWAIQZOrkPZnSqomIo9XfDLq3fToftjBapZur983+c6kyBqcfqTy3FVZ26FE2wE=,iv:00Qbw4nLASBnDh4hu5wLC/INpjykUEXM8uRTUSaqsMY=,tag:D3DXlVNw8OatMt+Ca9CKCA==,type:str]
  version: 3.13.0
