apiVersion: v1
kind: Secret
metadata:
  name: searxng-secret
  namespace: searxng
type: Opaque
stringData:
  secret_key: ENC[AES256_GCM,data:d+sVgNi2rMJvaRhox1u2rMHd0vsvazUKSIGNmlJIxgGIIO9vhKmVYVbTK/4kBA+8LtCHWfG4Pp3gnIVoW21yRg==,iv:nQ16A5r3tX+B+Eh+umpXi32LyPcm5O9H+7RG8hdhQnY=,tag:vDlTHUQxNNl3QibD7Q9/Pg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQXpZVVZNaFRNQTJxQTNx
        QzltOWtuRXlZaWp5WG1TTTZMcGJJQkJkWFRJCnJrbUJoQ3hCK1dpNHB6RGdNUTVm
        a3dmSFJJVkNwNjRZdXlXYUVvNHNjZnMKLS0tIENUNHRTV292QldSK2ZhaTNCR3hZ
        RFRlemFXVTQ1WlBoV0JhLzhqTHg3MVkKNevUf4hsZXp/8YZKdv/5k90WLow3b7Ix
        R0eNOHgGPaZPgWKZLhZeqaRU0I78iK2yCxDfiallVfrcHdpEkgEesA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n0cqvlyfca7gjasrmj4668gn9e3pak8fep0e84cvnpc3srt8zffqn4fs74
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNUpKOXNFUG9TaEMwaU5Y
        OG9JdWpqRUdTNGV0NHdmYjMwRDZCcmpWOFg0CllMNXRlczhGYmg4SGZhVVlycHBl
        YW5IZTAyczZUMmhKWUI2c3FkcmJyUncKLS0tIDlIbG5lVVdJTGFtMDI5cWUyOU1a
        R2dQVHd0d0JzTXVKcTA0T2Y3bStZUE0KCY8Iao04Xmk0vRLsGffKM9fxL7U/OEoM
        yqWriDjHlDtFuf3lKkp3tM6F1Gdvx71Z+7AAdFHNKGCE+pKR3rwKoQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10yse6kg99dwtsjaq4l7umdheecwsznpk4dnu76ff5jmjuka8uv9se4ysq2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T21:54:52Z"
  mac: ENC[AES256_GCM,data:u46N8ZYW7f7NcZaRkjgf9ZNDybo5wratNbuC1ApacTzjjAsIPkkZ+QgTaIh/Dg/Vy4TAOsVMwZtTn818hsz9RTR1oPJOjDt/o4E9mVMz/J5zu8Qr6YQebaQE7YBtlYvZlsS1wMU8eJ0recxFtCqEl3u4cT7rnn2DkxK60gjsmMo=,iv:+1D+xsB3vVmPvOMvvt+n3LNv7dJZSbhsuE9uJ/OIFFM=,tag:8B8C3m0HsCN2ogcMCCEOxw==,type:str]
  version: 3.13.0
