apiVersion: v1
kind: Secret
metadata:
  name: navidrome-secret
  namespace: navidrome
type: Opaque
stringData:
  ND_LASTFM_APIKEY: ENC[AES256_GCM,data:Yopq0OBg/RnJwdVXCs4tqMfl8LC6LW5rFvQKPZUwlm4=,iv:kp7xklcSikhRNyoh4yr5BvKWG354kkibyt32nMT/4Ww=,tag:Z+bRT0rY+d0iVXw1JZ8nTQ==,type:str]
  ND_LASTFM_SECRET: ENC[AES256_GCM,data:4Pn06XjsNfxhvPMS+Iv1WLY6GKnGGnHMEosxiHaK0qA=,iv:/3mvaTgEbQDHiqhAOzxhiuL9pPyqkqSOpVfeHgWzVzs=,tag:LF3vyaM0v/KUS83L8zaE4A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUTFETnBDd3dlQ1V2bWp0
        MnQ4MjhSWk1zSUdtZmJnTVozR1djWExwV0F3CkJZeURkRjdGaWt2RmxGZjJSZ05w
        aFZNd1c1ckt1K2lVeDVxek9sMUkzOVUKLS0tIFVabzJpRklscTgxdThBcVE0eCtu
        b0wwUjh5S3lPYXRHcFVoZTZrUkxtZlkKEYXVRTVjhbCIN6kdV+fo+tq9eQs3sfKe
        cy3XOazit48gubxYcOD2IG+jKN5MHHLughOgCDQJCbLrw1wrgB2H5w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n0cqvlyfca7gjasrmj4668gn9e3pak8fep0e84cvnpc3srt8zffqn4fs74
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UHNqK3NLMi9HNVdUUzBS
        dzFSbit1bnpQSlg0ejczSkNVQjdwVzJITndrCk40V0hIWm5YNFdhbkJDeFlMRHlR
        VTVEYnJPM2tXamFpdnJCT0JGY1RPRlUKLS0tIFNRL01oU2J6TjVlVVQvZUdxTGdI
        OUt2T21KL0txNC9qQS94RDQxNXJsS2MK3APxK629rk3tTyeqRC6+KfEFl/zGUqZo
        I+W1F6rfz5HiEr8xBqQH0voC4W8nBKfWAXHssszLsglzuUHM08o7hw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10yse6kg99dwtsjaq4l7umdheecwsznpk4dnu76ff5jmjuka8uv9se4ysq2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T21:47:27Z"
  mac: ENC[AES256_GCM,data:vFnmTbvA92lS/arEYn83Yz6t8QtgcoO8pe3SQiu1505UfrbtWVFTfKc127i3AdC+nn/4DRScnuGnAStmY594Y8RNCoNVj0JHvkYsuTf7h5+BRHn5s8MJXtQKipsPse1W5gwS/d/xKOChRMU0KDE4EYjChBjEan4pTRAhNwDGWb8=,iv:1QGnc3zfeuVGBiLNJR6lHMIw/lA5bJxzPI/CnHlf3go=,tag:asb8jQt4cBXYwxgOh7zU+g==,type:str]
  version: 3.13.0
