apiVersion: v1
kind: Secret
metadata:
  name: navidrome-secret
  namespace: navidrome
type: Opaque
stringData:
  ND_LASTFM_APIKEY: ENC[AES256_GCM,data:Yopq0OBg/RnJwdVXCs4tqMfl8LC6LW5rFvQKPZUwlm4=,iv:kp7xklcSikhRNyoh4yr5BvKWG354kkibyt32nMT/4Ww=,tag:Z+bRT0rY+d0iVXw1JZ8nTQ==,type:str]
  ND_LASTFM_SECRET: ENC[AES256_GCM,data:4Pn06XjsNfxhvPMS+Iv1WLY6GKnGGnHMEosxiHaK0qA=,iv:/3mvaTgEbQDHiqhAOzxhiuL9pPyqkqSOpVfeHgWzVzs=,tag:LF3vyaM0v/KUS83L8zaE4A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrYXJPaG9USVNNOWJjK2VJ
        Y1ZFQkxONXcvQ25DU05MWC9JMTdDU3JJblFNClE2Vkh2S29Ib0ZGc1d2UVRoZHJ6
        WkRHWGlUZ3pCczdlaGlaOUtYS2pVNFEKLS0tIEorZmh0czNVQWszR0s0dk9jaXFH
        Tm9MQkN0VTh1Ly9iMCt2SE5yV1hkdGsKjJfcv0vP+vRIVNM9DvI0PDVVPb1Fwopy
        MvyHTfVPfTYgdzdT1ioi9KQpOABPmZpLTwV6bg3GFQOMbvuW+E71KQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1m8j9egmweu9c8cpz2yejsulpzy82227eceh9awergehk5pflwfsslu4nah
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T21:47:27Z"
  mac: ENC[AES256_GCM,data:vFnmTbvA92lS/arEYn83Yz6t8QtgcoO8pe3SQiu1505UfrbtWVFTfKc127i3AdC+nn/4DRScnuGnAStmY594Y8RNCoNVj0JHvkYsuTf7h5+BRHn5s8MJXtQKipsPse1W5gwS/d/xKOChRMU0KDE4EYjChBjEan4pTRAhNwDGWb8=,iv:1QGnc3zfeuVGBiLNJR6lHMIw/lA5bJxzPI/CnHlf3go=,tag:asb8jQt4cBXYwxgOh7zU+g==,type:str]
  version: 3.13.0
