apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: ENC[AES256_GCM,data:+B7J,iv:MLvwNRnNGES2KdTrBUbVg1OGpZH2xfYZwQvx5DzNHjY=,tag:6sxGH49zvTb6awWM+pfQKg==,type:str]
  url: ENC[AES256_GCM,data:B1Kvto7qSITZT3KA4GyoVNf9g+PbRYqi3y3BuNchvvYj8S6+skUHnhV6c2g1,iv:e2Q4BHVnSuAo9FnixcDzl0ubMGPUic5Hm4B8gJXD8+I=,tag:fWlusXA+FMN9FdHoPJobjw==,type:str]
  sshPrivateKey: ENC[AES256_GCM,data:B7wC1TXZ0S2pTH55wfsT9PabIk3TSe+4hBLi92htLZIUqb+1nlpXxP7+1uW+TZ8bh91dC3AnNdAaTR+slYee9isLkUXjs9zmqNSoaLeHVgtYkTPimAB7nPp3xHhvUaTOKUjfSNUf0Fm4Juv9674vBJh/7iZ0Sa4IoPM/JUkwXCH6QR/RPORdlVlwx/8DNCbv4D9aBsl6XzHinc34MDp3RqCFeH7QXbKgk5wsfSa/VymJ9AGi2QqUPyjR2VY479zlmOyy3kDgjoFNofeWoQEQvhaprRqdmtY821Axm8wj1lK/6wM8miNShuzE5zKKD6s3LM1odfTRZE/RlCtJcw99XoUFXb0VSHp85+28s63OCAN01QvEcYTgg/gD6m8MSWb8vtUN9a1qPxKdSYa4WvONis3EvMLmIIXhjkVe6dgn7ctoFenYWcLxvh9dIoVls3ewmt7BsGvdzLR4/BHR8LuIaparyiTr+44Xu7FsitOiOT+VlglWOQIxYBEY6k+JunWGrHr9i7de7oUhO/9Z/p3P+57+TyYv0+65wJo=,iv:zkeVlmSj3lqz//glS0duOvAH2D4c+gk+H0FL60Mnizs=,tag:FShc+PQ3ezanI5Vyb/G9JA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3elhGdzJNdnlDYXhuTVdF
        V2QvVWZlMm14ZHp3K0RFN2lMeStBYmZrSGtjCkczOFpvUktPSjY5TVRjYnowQkVZ
        cHlYWnh0UFZGbk1SeTNCMUxmb0ZOUjQKLS0tIG81WExuYm85MGUyQ0pmNjIvMHZG
        SmtKTkZZa052M0h1bU0rTlVzWGRsZXcKENmKnwjRBgD1cka1g/jM1dNIBweHwsyB
        Dbtt/Qc7nRiiS9OZv7uLJ3IfZFnm12/97V+bLYCXeOr1X1dy6LfQDw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1m8j9egmweu9c8cpz2yejsulpzy82227eceh9awergehk5pflwfsslu4nah
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-24T20:36:54Z"
  mac: ENC[AES256_GCM,data:dNl13BETM0u+G8JbDYq7nKMF/6ogjAtVIXwsK8de45ZsFW44oyGlOalldETQyFua6Oixc/Pqp8RYWBThE5vOXiwGjeKngOSWy7nwVQQD33ZcXbanrdlC3SlsGzwKakFsT+ug0tr+c86nEqflapCA2SRz5gMSWXp9SZPjcHTsdzI=,iv:dXVifY4FYn3B6cZkS0BA/BowblFcVULqZ8VbkexuzKI=,tag:yebCNC4qZ5LLwhJU2PJ7MQ==,type:str]
  version: 3.13.0
