template_id: 299
vm_user: "hddq"
my_ssh_key: "{{ lookup('file', '~/.ssh/hddq-key.pub') }}"
inventory_file: "../inventory/hosts.ini"

default_vm_ram: 8192
default_vm_balloon: 6144
default_vm_balloon_shares: 1000
default_vm_cores: 2
default_vm_disk: "20G"
default_vm_storage: "local-zfs"
default_vm_gateway: "192.168.20.1"
default_vm_vlan: 20
default_vm_dns:
  - "1.1.1.1"
  - "8.8.8.8"

vms_to_provision:
  - name: "k8s-cp-1"
    vmid: 211
    ip: "192.168.20.111"
    k3s_role: "master"
    run_workloads: false

  - name: "k8s-worker-1"
    vmid: 212
    ip: "192.168.20.112"
    k3s_role: "worker"
    
  - name: "k8s-worker-2"
    vmid: 213
    ip: "192.168.20.113"
    k3s_role: "worker"