---
apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: default
  namespace: longhorn-system
spec:
  backupTargetURL: "nfs://192.168.20.12:/mnt/ssd1/backup/longhorn"
  credentialSecret: ""
  pollInterval: "300s"

---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: daily-backup
  namespace: longhorn-system
spec:
  cron: "0 1 * * *"
  task: "backup"
  groups:
    - default
  retain: 7
  concurrency: 2
