---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-auth-secret
  namespace: longhorn-system
spec:
  encryptedData:
    # gitleaks:allow
    users: AgCvBHLvKB7QRp7wVQnvdDDToWnoR+GYwbBo7FYgcsK+AAolAftKU1eoU/7BD+u4dJq2l1hGorZ8nqYMLqzA/HspmmZIR+FL0iEI0JWFlG8o9iwZ9vXuGB4Nmk2HJbjZ3mB8sLBDNUyEC7ST/iQOJZv4Rr7p5K9tW4bh+xNcAtsFRBcLyFydKazsmxcdwPbM/zGv70MgzCipHvBBhKrQyuMRHE2kxAoEZfl1Z8USrHZcU8YSm51KfEEdz+jFa+ph36x3iSgu1+Sk4yT61IW9c8Ui95F8ELfRFCfX56O62olBnvUA5ru6UFWK51IX62wKotLWUp2WoFTlIWzPE+0BovUt71dZfk+3f+vsLNhTmSCtMpYaVROzBxxMI2XVBYaGJ/SWMdvIItXayjdLEt/Wh54rGv02TWzfcvf5WZLjG9qrVjYKE0JC0/JmQ6ZPHMeo6zncjKA/gcQIi9C7FnSUXR9wr49/NYGuDy0BYSU0rOpIjwuLoQ5wmv+D1l7zDI0ftlMbUfZteC54CyZlpOw37EJf1uXjtN1Svd78yAgokmcHpVw7DlH65hwy9NfvIDDfIdM48iIRpxTlBvEam/Ps/aQyYyJie6HOQfzNF3CfawrQTk2yLXy5Q6qHEAYIjCMrAlOkI/9WKOuHcFcsQzGCyPXEKLBISzNA8x2xmK4FzNbwbztzXKCwmMPkpw0XSPpolAJmPQ5D5YPiSkR+8pTX5KTGUqO77Bib4WFG9znTQ/nSeCme9UxMlhTsjZvX
  template:
    metadata:
      name: longhorn-auth-secret
      namespace: longhorn-system
