---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: restic-htpasswd
  namespace: restic
spec:
  encryptedData:
    .htpasswd: AgBQt/qNg9GQaoyvl7hs8sBhzKwkuwBVFBlTT2rOYDsN8kTMF1PvUYUf09DPMkmt27ci4htCmdwu9BUI7djnIZ9qgx5M6Fgy4pyajvwBePkSMHa80CDDMTkezyU1V2u4hItWm4RpIq4CWqgbYonxUfzXKsKq2dwaJcGDmaxBjtIVeMTRcLtB3SIV7VFe7e3DMlU+NLu+a77aBENZnEACO2+vmf3lOKc+x80342WEzUPPC22tymSpOEpHVzhe141EBkc4KyhnC4AyzcvUS17XHzy2FouGFxtLhxalxDNfQxoX0FkYohUIiZzEf1+9eVB4MQsgkgWLL8C38N9y8jiLzymhLqYYieAP9MtJPccw8JVQnYv9yZsGv0oXiN0fG7Lqa0DvWPr053fVgx/dJNoixZlWlIrce6Urr6Jzlr8NMpBj4Zn8smqG7OaUy8qgIoqLyMGsjpFabs23ltlF1kzQKxpnAGNXlWA+ckrcemdY5gYgsc5Q9Q5Fd2btH/Jj/X/q+/MRaOnzB9gQMb8CnTTI2F3aeEXVnCYsriBqpOpjNRKWVMhbUFOqgKPw2edHIkuNSLLMAdPOsfuyEOXBlwgsP+7rpy0JUVmbj1Daqpp9MoeeDnraT79X4mXud2EwROXEOu2tTjgmmJMaLve3MdOjTj0c1jy2IEh6JC2kUPPoE8C7cdfIugETHy9KmD2FaLxz7BXiTXCA7YJdn+ZB7PF9vwdHBX3wZDuPeMTeC+AEXRuynt2ZyfNS2JYIsHvB3Gupa//3YLihF6kdRKDJYg4AM6bO47FFmzwyczdcZ6z6Xhk6HI5vPSTgOcVrFPMkpZ0Giy239AL+NkZQH7eQUKk6UV6m58LDLV8GMsqStgkPWeTbxT8bpA== # gitleaks:allow
  template:
    metadata:
      name: restic-htpasswd
      namespace: restic
    type: Opaque
