apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
  admin.password: ENC[AES256_GCM,data:xlEbYHGYu9iOf3N8DNRcKqaxHuwffUrGppoGOU79E6FJbQQObT3A3FOWWHrkO1cNweYstIHh/FVzOw4O,iv:h+jwC5pZ7fBS6voLm54Q+3nXrZCIrQnfbRL0PBLYfMo=,tag:++JzMqYcAJ0IjTWskaLLxQ==,type:str]
  admin.passwordMtime: ENC[AES256_GCM,data:PPk//XeogKqq7NvQUzYPJjv5WKg=,iv:llXyN47aPZhZ4QE+4j83w43jWI70JgJSmcmIns8yF9U=,tag:3h/62NOfPi0E6+E6l3SnXQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdDhLRGcrQ2t3MDhtdW8z
        NzVMMjlYTk82NCtCZU9QcmZxUmRadkxTSTEwCkMzOFlSVHFmUnROWFpaLzdMc0FJ
        eXVJdWxLR0JkazZGckwzNXc0bXhhUE0KLS0tIHJ6ZmFUeDR5U2NLaUpaU1BTOGZP
        NzVUckFtUnpYWmVYb3VoTUVoNXNrRFkKE/m8d1Etir2rtuElPxGQ9FwQnbAnSCwk
        hN18Wr2Y96Y5DzxtV4WdRpHwKR3HYK5+vj1kXemMy0VyvWbYxtq2+g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n0cqvlyfca7gjasrmj4668gn9e3pak8fep0e84cvnpc3srt8zffqn4fs74
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzN2grRWltWjZqWFUyYWE1
        cjlrejFJR2hEaWVsWElKZDFUUVRGOGcrT0JBCkYyVWVCTjhmeEFnazk4bEM4ZWZy
        N0xodHNyWXVwTGNUWURiejB4bUh1RnMKLS0tIEgwdXVrNEQxQlNWTXZ5MTMwTGhs
        SlRTaXVGSlEvdDlTR2pVaFp4clYzMkkKZGsebovDZ52xuJu8x8KNrX7oX2xyev6I
        xc1uafEunA2VEt1kO/r2BE/r8unfxLl+LbGhjWzcxOEah4HXQ9Kksw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10yse6kg99dwtsjaq4l7umdheecwsznpk4dnu76ff5jmjuka8uv9se4ysq2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-06T21:57:47Z"
  mac: ENC[AES256_GCM,data:4B2GfY08Xb+alkzSnQXYtwsg4oBktoiLSWI4+pobuD1WLup0hFkZHC4aZkZWpKSJCGzEW5vZbu3qIKoyuciB4h1Zf3fTqJ9aB91PbYGEd9Lu5VIZ7pv87keDiIwMt4zQjvKyawJiunK5Db5PfYT3coT/QOx36EkCJ0V3cxqhCA4=,iv:HQz01Qhck6Vs+ubTPXA1t0M4GYtl9mpdFIXsaRezjCY=,tag:QFoaWKkyGkDu9YkjOuI8Vw==,type:str]
  version: 3.13.3
