apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: ENC[AES256_GCM,data:+B7J,iv:MLvwNRnNGES2KdTrBUbVg1OGpZH2xfYZwQvx5DzNHjY=,tag:6sxGH49zvTb6awWM+pfQKg==,type:str]
  url: ENC[AES256_GCM,data:B1Kvto7qSITZT3KA4GyoVNf9g+PbRYqi3y3BuNchvvYj8S6+skUHnhV6c2g1,iv:e2Q4BHVnSuAo9FnixcDzl0ubMGPUic5Hm4B8gJXD8+I=,tag:fWlusXA+FMN9FdHoPJobjw==,type:str]
  sshPrivateKey: ENC[AES256_GCM,data:B7wC1TXZ0S2pTH55wfsT9PabIk3TSe+4hBLi92htLZIUqb+1nlpXxP7+1uW+TZ8bh91dC3AnNdAaTR+slYee9isLkUXjs9zmqNSoaLeHVgtYkTPimAB7nPp3xHhvUaTOKUjfSNUf0Fm4Juv9674vBJh/7iZ0Sa4IoPM/JUkwXCH6QR/RPORdlVlwx/8DNCbv4D9aBsl6XzHinc34MDp3RqCFeH7QXbKgk5wsfSa/VymJ9AGi2QqUPyjR2VY479zlmOyy3kDgjoFNofeWoQEQvhaprRqdmtY821Axm8wj1lK/6wM8miNShuzE5zKKD6s3LM1odfTRZE/RlCtJcw99XoUFXb0VSHp85+28s63OCAN01QvEcYTgg/gD6m8MSWb8vtUN9a1qPxKdSYa4WvONis3EvMLmIIXhjkVe6dgn7ctoFenYWcLxvh9dIoVls3ewmt7BsGvdzLR4/BHR8LuIaparyiTr+44Xu7FsitOiOT+VlglWOQIxYBEY6k+JunWGrHr9i7de7oUhO/9Z/p3P+57+TyYv0+65wJo=,iv:zkeVlmSj3lqz//glS0duOvAH2D4c+gk+H0FL60Mnizs=,tag:FShc+PQ3ezanI5Vyb/G9JA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzT2ZOTmRhWEttSWtWc3Ry
        UDFGUXgxS1drS3g5SGpQa3lWUS9LRG0xTTE0ClNTbkhmVXZ3NkN1VkRMb05XRXoz
        amg3eEFIZkNBSHBzYS9JVTlXSU1NbEEKLS0tIERLN25PNTgvbGgyMGhlMXRRYzJG
        bXE1OVRvMFhuUDI2SUFHWU8wQXRIK0UKtmGStxK4yXqiI3qJc+hNG79IQ7afBmwy
        VusJ+VYv77UVhnPdaQJyqiINNbC31O3HJwpZscx4+cy0g/V5Um0jeQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n0cqvlyfca7gjasrmj4668gn9e3pak8fep0e84cvnpc3srt8zffqn4fs74
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3S0FCV2x5cXJWYVpUWUJy
        NUZ1Vno0ejlsNlJQSHhuK052cTI5dlhadTNVCmFJMXhDdjcxcHJIRXNVZHg3VmV4
        S2FqcVNHclA1bGIvczBnUUM4cktMNzAKLS0tIDV5M0Voc0tzQVFpbnQ4L20weUFy
        U2lJL3VIWU5SbFBQZUhKQ01hQkhPZFUK2yRB0g+MF3tau1FpN63h0FHDE6ihXXpp
        4gP0901E2CnEADNFpXKgzUtrBrKy4q17NUJfVoYS0ffn1Tx6wx+aHw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10yse6kg99dwtsjaq4l7umdheecwsznpk4dnu76ff5jmjuka8uv9se4ysq2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-24T20:36:54Z"
  mac: ENC[AES256_GCM,data:dNl13BETM0u+G8JbDYq7nKMF/6ogjAtVIXwsK8de45ZsFW44oyGlOalldETQyFua6Oixc/Pqp8RYWBThE5vOXiwGjeKngOSWy7nwVQQD33ZcXbanrdlC3SlsGzwKakFsT+ug0tr+c86nEqflapCA2SRz5gMSWXp9SZPjcHTsdzI=,iv:dXVifY4FYn3B6cZkS0BA/BowblFcVULqZ8VbkexuzKI=,tag:yebCNC4qZ5LLwhJU2PJ7MQ==,type:str]
  version: 3.13.0
