homelab:
  baseDomain: hddq-k8s.duckdns.org
  serviceIps:
    graphiteExporter: 192.168.41.12

grafana:
  ingress:
    hosts:
      - grafana.hddq-k8s.duckdns.org

alertmanager:
  ingress:
    hosts:
      - host: alertmanager.hddq-k8s.duckdns.org
        paths:
          - path: /
            pathType: ImplementationSpecific
