kube-prometheus-stack:
  coreDns:
    enabled: false
  kubeDns:
    enabled: false
  kubeControllerManager:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeProxy:
    enabled: false
  kubeEtcd:
    enabled: false

  grafana:
    enabled: false
    # adminPassword: "admin123"
    # persistence:
    #   enabled: true
    #   storageClassName: longhorn
    #   size: 2Gi
    # deploymentStrategy:
    #   type: Recreate
    #   rollingUpdate: null
    # ingress:
    #   enabled: true
    #   ingressClassName: infrastructure-traefik
    #   hosts:
    #     - grafana.hddq-k8s.duckdns.org

  prometheus:
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: longhorn
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 5Gi
      resources:
        requests:
          memory: 400Mi
        limits:
          memory: 2Gi
    prometheusOperator:
      admissionWebhooks:
        enabled: false
        patch:
          enabled: false
