---
- name: 🏗️ Provision New VM on Proxmox
  hosts: localhost
  gather_facts: false
  vars_files:
    - "../secrets.yaml"
  vars:
    # --- PROXMOX CONNECTION ---
    proxmox_api_host: "192.168.20.10"
    proxmox_node: "z690"
    proxmox_api_user: "root@pam"
    proxmox_api_token_id: "ansible"
    # --- VM SPEC ---
    template_id: 299
    new_vm_id: 298
    new_vm_name: "ansible-test"
    new_vm_ip: "192.168.20.111"
    new_vm_gateway: "192.168.20.1"
    vm_user: "hddq"
    vm_dns: 
      - "1.1.1.1"
      - "8.8.8.8"
    vm_disk_size: "20G"
    vm_memory: 4096
    vm_cores: 2
    my_ssh_key: "{{ lookup('file', '~/.ssh/hddq-key.pub') }}" 

  tasks:
    - name: 🐑 Stage 1 - Clone VM from Template
      community.proxmox.proxmox_kvm:
        api_host: "{{ proxmox_api_host }}"
        api_user: "{{ proxmox_api_user }}"
        api_token_id: "{{ proxmox_api_token_id }}"
        api_token_secret: "{{ proxmox_api_token_secret }}"
        validate_certs: false
        node: "{{ proxmox_node }}"
        clone: yes
        vmid: "{{ template_id }}"
        newid: "{{ new_vm_id }}"
        name: "{{ new_vm_name }}"
        target: "{{ proxmox_node }}"
        format: raw
        full: yes
        timeout: 500
        state: present

    - name: 💉 Stage 2 - Inject Cloud-Init Config
      community.proxmox.proxmox_kvm:
        api_host: "{{ proxmox_api_host }}"
        api_user: "{{ proxmox_api_user }}"
        api_token_id: "{{ proxmox_api_token_id }}"
        api_token_secret: "{{ proxmox_api_token_secret }}"
        validate_certs: false
        node: "{{ proxmox_node }}"
        vmid: "{{ new_vm_id }}"
        state: present
        update: yes
        ciuser: "{{ vm_user }}"
        sshkeys: "{{ my_ssh_key }}"
        ipconfig:
          ipconfig0: "ip={{ new_vm_ip }}/24,gw={{ new_vm_gateway }}"
        nameservers: "{{ vm_dns }}"
        memory: "{{ vm_memory }}"
        cores: "{{ vm_cores }}"

    - name: 💿 Stage 3 - Resize Disk
      community.proxmox.proxmox_disk:
       api_host: "{{ proxmox_api_host }}"
       api_user: "{{ proxmox_api_user }}"
       api_token_id: "{{ proxmox_api_token_id }}"
       api_token_secret: "{{ proxmox_api_token_secret }}"
       validate_certs: false
       vmid: "{{ new_vm_id }}"
       disk: "scsi0"
       size: "{{ vm_disk_size }}"
       state: resized

    - name: 🚀 Stage 4 - Power On
      community.proxmox.proxmox_kvm:
        api_host: "{{ proxmox_api_host }}"
        api_user: "{{ proxmox_api_user }}"
        api_token_id: "{{ proxmox_api_token_id }}"
        api_token_secret: "{{ proxmox_api_token_secret }}"
        validate_certs: false
        node: "{{ proxmox_node }}"
        vmid: "{{ new_vm_id }}"
        state: started

    - name: ⏳ Stage 5 - Wait for SSH
      wait_for:
        host: "{{ new_vm_ip }}"
        port: 22
        delay: 5
        timeout: 300
        search_regex: OpenSSH
      connection: local