---
- name: 👑 Initialize K3s First Master
  hosts: k3s_new_nodes[0]
  become: true
  gather_facts: true
  tasks:
    - name: 📥 Install K3s Server (Cluster Init)
      shell: curl -sfL https://get.k3s.io | sh -s - server --cluster-init
      args:
        creates: /etc/rancher/k3s/k3s.yaml
      environment:
        {}

    - name: ⏳ Wait for Node Token
      wait_for:
        path: /var/lib/rancher/k3s/server/node-token

    - name: 🔑 Read Node Token
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: node_token

    - name: 💾 Set Fact for Token
      set_fact:
        k3s_token: "{{ node_token['content'] | b64decode | trim }}"

- name: 🤝 Join Additional Masters
  hosts: k3s_new_nodes[1:]
  become: true
  gather_facts: true
  vars:
    master_ip: "{{ hostvars[groups['k3s_new_nodes'][0]]['inventory_hostname'] }}"
    k3s_token: "{{ hostvars[groups['k3s_new_nodes'][0]]['k3s_token'] }}"
  tasks:
    - name: 🔍 Debug Connection Params
      debug:
        msg: "Joining cluster as SERVER at https://{{ master_ip }}:6443..."

    - name: 📥 Install K3s Server (Join)
      shell: "curl -sfL https://get.k3s.io | K3S_URL=https://{{ master_ip }}:6443 K3S_TOKEN={{ k3s_token }} sh -s - server"
      args:
        creates: /etc/systemd/system/k3s.service

- name: ⚙️ Configure Local Access
  hosts: k3s_new_nodes[0]
  become: true
  tasks:
    - name: 📥 Fetch Kubeconfig
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ../../kubeconfig
        flat: yes

    - name: 📝 Update Kubeconfig Server Address
      delegate_to: localhost
      become: false
      replace:
        path: ../../kubeconfig
        regexp: '127.0.0.1'
        replace: "{{ inventory_hostname }}"

    - name: ℹ️ Instructions
      debug:
        msg: "HA Cluster installed! All nodes are masters. Config saved to 'kubeconfig'."