victoria-metrics-alert:
  server:
    datasource:
      url: "http://vm-single-server.monitoring.svc.cluster.local:8428"

    notifier:
      alertmanager:
        url: "http://infrastructure-alertmanager.monitoring.svc.cluster.local:9093"

    config:
      alerts:
        groups:
          - name: hardware-alerts
            rules:
              - alert: HostOutOfDiskSpace
                expr: (node_filesystem_avail_bytes{fstype=~"ext4|xfs|btrfs|zfs", mountpoint!~"/boot|/boot/efi"} / node_filesystem_size_bytes) * 100 < 15
                for: 1m
                labels:
                  severity: warning
                annotations:
                  summary: "Disk space running low on {{ $labels.instance }}"
                  description: "Less than 15% free space left on volume {{ $labels.mountpoint }}."

              - alert: HostOutOfMemory
                expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100 < 15
                for: 1m
                labels:
                  severity: warning
                annotations:
                  summary: "Memory running low on {{ $labels.instance }}"
                  description: "Available RAM is under 15%."

              - alert: NodeDown
                expr: up{job=~".*node-exporter.*"} == 0
                for: 1m
                labels:
                  severity: critical
                annotations:
                  summary: "Node {{ $labels.instance }} is down"
                  description: "node-exporter scrape failed for 1 minute. The server is unreachable or the agent crashed."

              - alert: HighLoad
                expr: node_load5 > count by (instance) (node_cpu_seconds_total{mode="idle"})
                for: 1m
                labels:
                  severity: warning
                annotations:
                  summary: "High CPU Load on {{ $labels.instance }}"
                  description: "5-minute load average is {{ $value }}, which exceeds the total number of CPU threads. System is getting saturated."
