homelab:
  baseDomain: stg.hddq.org
  wildcardCert:
    name: stg-hddq-wildcard
    secretName: stg-hddq-wildcard-tls
    issuerName: cloudflare-letsencrypt-prod

traefik:
  service:
    annotations:
      lbipam.cilium.io/ips: "192.168.42.10"
