apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: unbound
  name: unbound
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unbound
  strategy: {}
  template:
    metadata:
      labels:
        app: unbound
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 100
        runAsGroup: 101
        fsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      containers:
      - image: alpinelinux/unbound
        name: unbound
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        ports:
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            memory: 128Mi
            cpu: 100m
        volumeMounts:
        - name: config
          mountPath: /etc/unbound/unbound.conf
          subPath: unbound.conf
        - name: unbound-run
          mountPath: /etc/unbound
      volumes:
      - name: config
        configMap:
          name: unbound-config
      - name: unbound-run
        emptyDir: {}
status: {}
