---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-telegram
  namespace: monitoring
spec:
  encryptedData:
    bot-token: AgA2iAIBtdZfF9SH//8lEraugE5jQ2aBYv38ghNTnPYJ9gDWy2XxkRhqvSHSmamB305rX4+pyYvQRBiRxFIo0ftcGJx7T3JUcvDcLFiZvqEm5TmJcFblPSGoKb7GAXMH7msrhhG6lSaw16u9VnXO40F4S0vYBoS2i+wid1Sfj9ex+51k7c00P4DkY1qQfeYwr7wVrIpN2lUejT7SZdU9U0ORz9dPYpqhYtPgeQQdWwlSGDhRy5alDFDIeGik53TzU77n83ZzFtipTr4a/ksdgbLU2LKcX8sHws8KZtDI0klDKsKVh2z+a+a52SMPsP8i9HLBzCWPt1rEinDdRbkPn2hBQ13RhDOZROMgD29bKLbBID8dN8QOo997V0jF3zs1OaykDksgLQ8uCMqz2oh6pz1MqmmvDJF0e/94FtbF2vBCJOma7NTij4DX4C6l6C2LOVvs76g9IjLhfokN4aDG5/1UHxAPo0f1X4qel8ryAji4u3vYWouj6S9WawPBYFZOa7PJz1VO2vQtHRx1U9dP+ZDk3b7hmzEJUi+2i7gSSzht+473UrJx2wTouD3VN8kJKQOitATn2hfMCV09QACiQId3O3ySsvVK35sgIYK7C0ton8WV8kkdUMQSItjx74C18HKjpFvCdv20u8Ob/Y2e6a7Rt/YUiRffY3WqaMlmPCNRlPQPh8Ki1LrCtckwB0QnZNDZEPHXco+kIFc/HVdUkNQJeWBNayJmt6PGfpydQNp/R9dFvWsMN0BDRA8RyiRB # gitleaks:allow
  template:
    metadata:
      name: alertmanager-telegram
      namespace: monitoring
