apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: openwrt-router
spec:
  myASN: {{ .Values.homelab.metallb.myASN }}
  dynamicASN: "external"
  peerAddress: {{ .Values.homelab.metallb.peerAddress }}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
spec:
  addresses:
    {{- range .Values.homelab.metallb.addressPool }}
    - {{ . }}
    {{- end }}
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: default-bgp
spec:
  ipAddressPools:
    - default-pool
