immich:
  defaultPodOptions:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - k8s-prod-cp-1
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      seccompProfile:
        type: RuntimeDefault
  server:
    ingress:
      main:
        enabled: true
        className: infra-traefik
        hosts:
          - host: immich.lab.hddq.org
            paths:
              - path: /
                service:
                  identifier: main
    controllers:
      main:
        containers:
          main:
            image:
              # renovate: datasource=docker depName=ghcr.io/immich-app/immich-server
              tag: v3.2.0
              digest: sha256:ae13784ffcfcce8f4178113eb6661602a1fd1912f3d539880b8ac0dd95fc8ac2
            env:
              DB_HOSTNAME: postgres-rw.postgres.svc.cluster.local
              DB_USERNAME: immich
              DB_DATABASE_NAME: immich
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: immich-postgres
                    key: password
  machine-learning:
    persistence:
      cache:
        enabled: true
        type: persistentVolumeClaim
        size: 10Gi
        accessMode: ReadWriteOnce
        storageClass: openebs-hostpath
    controllers:
      main:
        containers:
          main:
            image:
              # renovate: datasource=docker depName=ghcr.io/immich-app/immich-machine-learning
              tag: v3.2.0
              digest: sha256:f8b2869891c861a58dde969d86e7ea8a186e6059a55886632ee3249e51fb574a
  valkey:
    enabled: true
  controllers:
    main:
      containers:
        main:
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

  immich:
    persistence:
      library:
        existingClaim: "immich-nfs-pvc"
  persistence:
    tmp:
      type: emptyDir
      globalMounts:
        - path: /tmp
  env:
    TZ: "Europe/Warsaw"
