immich:
  defaultPodOptions:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - k8s-prod-cp-1
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      seccompProfile:
        type: RuntimeDefault
  server:
    ingress:
      main:
        enabled: true
        className: infra-traefik
        hosts:
          - host: immich.lab.hddq.org
            paths:
              - path: /
                service:
                  identifier: main
    controllers:
      main:
        containers:
          main:
            image:
              # renovate: datasource=docker depName=ghcr.io/immich-app/immich-server
              tag: v3.2.4
              digest: sha256:d317916b28090c33eb36b308464ea391f8b7df1d850fcfea227a39ec879718c2
            env:
              DB_HOSTNAME: postgres-rw.postgres.svc.cluster.local
              DB_USERNAME: immich
              DB_DATABASE_NAME: immich
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: immich-postgres
                    key: password
  machine-learning:
    persistence:
      cache:
        enabled: true
        type: persistentVolumeClaim
        size: 10Gi
        accessMode: ReadWriteOnce
        storageClass: openebs-hostpath
        annotations:
          k8up.io/backup: "false"
    controllers:
      main:
        containers:
          main:
            image:
              # renovate: datasource=docker depName=ghcr.io/immich-app/immich-machine-learning
              tag: v3.2.4
              digest: sha256:e16c2f166a8174901959fdf85e2e4c7bd1ebc4b37e0b6655de97c41408a260c4
  valkey:
    enabled: true
  controllers:
    main:
      containers:
        main:
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

  immich:
    persistence:
      library:
        existingClaim: "immich-nfs-pvc"
  persistence:
    tmp:
      type: emptyDir
      globalMounts:
        - path: /tmp
  env:
    TZ: "Europe/Warsaw"
