apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-telegram
  namespace: monitoring
type: Opaque
stringData:
  bot-token: ENC[AES256_GCM,data:PFw24KYok6CLWc3damy8VVW6ml0gdHFzHtCGv6pYSnUiZhMa9MQrLLjIwm9N+A==,iv:J/8Tz4B9pPGWNvky0ODr6+XTK2duRJozLBYREdZeers=,tag:NQxPlyJw0Xt4iDmWUo2hcA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUENIMG84bmxSQ0lzc1p0
        R3Nic0VBSG9LZFBDVGhTTTUyZDRVWmlnNVZ3Ck9ha3pFSmVWclNMK2xva0lkcmlX
        OUpiQzh4SFI0UCtWdno5ak5GcGRPUWcKLS0tIHZpdFRyc2k3Q2RDRXJpcThzOXB1
        bjVucDhadEsrVHp1OXZJSHFVdFN0M2cK3VbHH6f+Ti9iBzsLjv/d+jqJCfgajZoG
        zXlJXiA/ezqn8LJ5QZMHMD18L7MybdAcBVNFlmdZbanDJeXgZgYXtw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n0cqvlyfca7gjasrmj4668gn9e3pak8fep0e84cvnpc3srt8zffqn4fs74
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SVFxUUdrbnpPL1NDeCta
        TThGS3RBa01xSmRZd1NoRlBLSU9UWG4zWEhnCnZ4N0RPVnE3MGEzOUZ5NHljOHJQ
        RnlnLzhyL0d3aGt3WEt4aVpBUnB1NVEKLS0tIE1aU3NQbDAvQWd1ZTJ5YVc1OHdo
        MXZYWFVhcHFPMU1LL3RNM3ZYbXNrL0UKCjju69D7SPJtOcKMRQEE5tdKx8QIR10H
        o1sTPeHRhzYFeBvTuqenf2S3e/TsDaAwbDb4lIH74W8csOrMEm7sUQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10yse6kg99dwtsjaq4l7umdheecwsznpk4dnu76ff5jmjuka8uv9se4ysq2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T21:04:07Z"
  mac: ENC[AES256_GCM,data:ZESq5kPRffc/6jn9RMtj0JUQI9hjOeWnmQM8sS++XhsLGEzk9E2EPJW4uMdbsBHg0k9xsmsjhWhKirrpRxcj4ZYyjFbhXApI27HMgE9fgSrGZoLmR2DugFjb8UrXhudqvi1/A5YMAUp3lLMZ2HqdJQW4RAOBdIeIxXPMvSf8LRw=,iv:WyLe1o+f9FkbRqePv0InO8SVo4ZFef0D/0kzDlvZM4s=,tag:t/sh8GjXrsN7C5/EB6FTUQ==,type:str]
  version: 3.13.0
