longhorn:
  longhornManager:
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
  longhornDriver:
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

  persistence:
    defaultClass: true
    defaultClassReplicaCount: 1
    defaultDataLocality: strict-local
    reclaimPolicy: Retain

  preUpgradeChecker:
    jobEnabled: false

  defaultSettings:
    createDefaultDiskLabeledNodes: true
    # kubectl label node NODE_NAME node.longhorn.io/create-default-disk=true
    taintToleration: "node-role.kubernetes.io/control-plane=true:NoSchedule"
    storageMinimalAvailablePercentage: 10
    defaultDataLocality: strict-local

  ingress:
    enabled: false

homelab:
  baseDomain: lab.hddq.org
