# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
clusterName: homelab-staging
endpoint: https://192.168.20.120:6443
allowSchedulingOnControlPlanes: true

talosVersion: v1.13.6
kubernetesVersion: v1.36.2

nodes:
  - hostname: k8s-staging-1
    ipAddress: 192.168.20.120
    controlPlane: true
    installDisk: /dev/vda
    patches:
      - "@./patches/vdb-config.yaml"
    networkInterfaces:
      - deviceSelector:
          physical: true
        dhcp: false
        addresses:
          - 192.168.20.120/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.20.1
    nameservers:
      - 192.168.70.2
      - 192.168.41.13
      - 1.1.1.1

controlPlane:
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/qemu-guest-agent
