apiVersion: v1
kind: Secret
metadata:
  name: pve-exporter-secret
  namespace: monitoring
type: Opaque
stringData:
  pve.yml: ENC[AES256_GCM,data:cm2cKgW2tC8uGbPThAWhQRajMf2/VJRTp2vZJEUo4GFsjcA0B/AckcvnSb/MSznqd8EDaegZmayYZupIlpHBTx1dR7ikW4L0l9toPK/yWkDjDrBnrFAtXV8okIeJkaNWXQW6D3TSHRJc4B/J70Ey4g6osSapDqDQBom7JWGdv9TbEIiq95Qsf7IXiDkjlUVe,iv:G+zJf7iytYJHHeUHSXIc7XsJjZGhrANB/S9FNNdaGKY=,tag:PBB/+ICKfDwlBxAaIy/9hQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVXZhbUxqM3dBTk1ucXRo
        UGJDZkI4VXNIOUpmYWhrU3JIVnorL0tSMEJnCitadXBtNzBKZ1VtS3kvWFAyTmRj
        VGZnUTFJYVcyMTZBaHYyTDJmWHgzVnMKLS0tIGdNd0VaN3pyL1ZNV1ZnUVU2MjNO
        QWF0T3pNbEtrbGlhUW1aK0wzQkRhUjAK0a0XvITVqFXNQaZpL8nebGbhI9COW0kj
        ZLfmrnHULEZroGUAM4RGeD779AEsRItWlbr09WjpzVqCEH6LsyzpTQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1m8j9egmweu9c8cpz2yejsulpzy82227eceh9awergehk5pflwfsslu4nah
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T21:11:30Z"
  mac: ENC[AES256_GCM,data:1Ub5L3GuWGS87yA+59fv6rLSJI76NE+62bBdF8cfcT3bUomtW3DVARdlww74Fds7ZCJrrFvSussaScWEveGsVqZo4pnJAHJn1dJb3fALu7DEagYXWLsbVefHjOfMBbjwkErQNjPOWLWb+AuKz9jzRwS9lu1udYyUvzkelI83pic=,iv:FdmEsMTnt4DWHuHqJQQVeM2IZVHg41ZRW+kJHZhNRJ0=,tag:IImWhu2KKYqe0jhZ8CxzXQ==,type:str]
  version: 3.13.0
