apiVersion: v1
kind: Secret
metadata:
  name: duckdns-secret
  namespace: cert-manager
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:gBMb3EUPoRIE73wVEA6tjp0Ugq/SMBH8P7hDOAMNVojpY7QA,iv:AukbRDUS6rTQCGsDIRWIOV8ij8EbLjoPFb9ZHOpj+L8=,tag:U24JbW2e6g+zzxVlXFT8kg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UDVzNWpFRTROeXdBSFI1
        YkpxVmVEU3gzVXF6Y2x4T2E3YW9saERlTXpnCnNwK3JoeC9obk5xcHd5OTJmMTFx
        YXBmRXZXS0NPZ2hSeWwxaWV6RmFrNEUKLS0tIDdDQTNRUmhZcFFsckxSd1pEYVVj
        YzR5RVR2K3RtTkQrWUphQSt2ZnpZY1EKehZS6Xm5n9IDWDmUJIt2u/0OaZxvTg30
        zI+uLJ+lhSWrMGF6wlA0u9ioLR3xYcOPC3Uz2UneS0+KL/pYKonAZw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1m8j9egmweu9c8cpz2yejsulpzy82227eceh9awergehk5pflwfsslu4nah
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-24T20:39:55Z"
  mac: ENC[AES256_GCM,data:mca+cIoYppDLlchDvxWsBd3ZrCrqS81w5Q1nN9kGh8q4ASlS0LacVZgknoH2XbsFbiSG/Qu8QJfKKhgAmCGrGo6saLmYwKjovObeFSmn7DoxJatYGiZIxkbqCTyBfmPvXeDDY9rqStuo981cU4YHInWQTyQy/3gqWPSYa25lqU8=,iv:bbhq8d8liujCw5yGEBeJw9FJsiBM4Z96GbL549Oojxc=,tag:6pTIiF0FYWnQ1XTUZGgSGQ==,type:str]
  version: 3.13.0
