victoria-metrics-single:
  server:
    fullnameOverride: "vm-single-server"
    persistentVolume:
      enabled: true
      storageClass: "longhorn"
      size: 10Gi

    service:
      type: ClusterIP
      servicePort: 8428

    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 512Mi

    retentionPeriod: 1 # month
