apiVersion: v2
name: alertmanager
description: A Helm chart for Prometheus Alertmanager
type: application
version: 1.0.0
appVersion: "v0.31.1"
dependencies:
  - name: alertmanager
    version: 1.33.1
    repository: https://prometheus-community.github.io/helm-charts
