alertmanager:
  enabled: true
  persistence:
    enabled: true
    storageClassName: longhorn
    size: 2Gi
  ingress:
    enabled: true
    className: infrastructure-traefik
    hosts:
      - host: alertmanager.hddq-k8s.duckdns.org
        paths:
          - path: /
            pathType: ImplementationSpecific

  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ["alertname"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: "telegram"
    receivers:
      - name: "telegram"
        telegram_configs:
          - bot_token_file: /etc/alertmanager/secrets/bot-token
            chat_id: -1003558340282
            message_thread_id: 3

  extraSecretMounts:
    - name: telegram-secret
      mountPath: /etc/alertmanager/secrets
      secretName: alertmanager-telegram
      readOnly: true
