---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAP7uADctFJpczKh4Usy3aWZZunSmsgypEBKsW6jHEiUI/0VXd+TasldT13FQAOl99FX4g/yoWbnKKk/dGCj5r6sydXlanBEIdX2zVJJc43WN0WcmoxSEX9/uXzwPvp4lSoWdv598yTLqhe1fTAw3de0bQO53ZV2rj/y9CDyK/USBp9MgdTw04CG9vQ5JZPsuHNSYP5M1PrTGChDE716jLmLeL17oFQZm2HYqbNU4sHs3Mx0gQmx9SFWqxNO7zbjXazl90VBA85UHzw/oRm1UpmUgj+533IfDawaSX0CIOcVOj82BGuiIOMEFHaLK0E5z4XJ9Xaw/EmPoPQ3C0NgQO2Y9Gdyofb2LKqhTdwckCtxzJ/qpi8pWzefmN5Ow7Fn+EKLzGSbMexkyxW/q0dsnvC+z5QrHX+250WNfcj7NrCVkjPU1glAtyuN6a6WaZhTOjmZ5a7kBdH7ieIC1o0ew2amJ+wl34SMM6FMgCOzIRmGV+MC7+oof7FX8Bgio/aTMjlC9jFsMApcjTjKlzHB6vufEHQ8wa98IULiIsBMIHoXAqOs43CdhUWm8bECVMxYNTuP4qIJoY+NB6pUPDE1nDV4ZtYQpuarJVi6vfTewHVIexPsf0fe2ip8XTT75hUiIO/dOEzhvTjI7CRxFOVKwJ51s/02a31ZAixfKtRaTjOCzAOpGiS+Vq47GK/fuT4F6DBw9uPsXTYmW8Zuiwx0XHO1PZcHGabmbPm4X0Q7HDSNLVYPdczRBx5 # gitleaks:allow
    admin-user: AgCuyHKHKmTj6aCD9iOeGOU/t5wpURvZWO4N/N4hmp8iz5eFdZDPzzD/4Wansjc1/TiuBS7tCH7geWyU/fezYnqOu02R3bTyw4lGUgAejzunq0cFwRqo3sQIW4Q54lBw5He00ePvrB75JuSX8Q+5u7CuAA9e7Txw4J28DVpaLlqbRPe5PP0VNCcnRVZDOLslIB+ci2tjXZyworzjNhjvDs02/5SLoTMmgi7ibEh93LW6CdpNFJTu0CyvzaKTjktKy6nkUom7OOwHZQEp+0yRRU9FwQk+ZHSxFbOl+fdn84akQnjb72JnV4LtdsZ35v7ZDTlnj6tkJSttKR/JUI+hgpuxMUt9Ljt0QCSbDefj6fVHI4fZsmqw0Izfnx6W5S7Pzh7BRMCBNBfotalGEX1e+1gZJCHlebZ8pqak4oXpGqNyrzg8QuuWJy9X81n9/ckrzVQWgcLDUF3v4XTHG/twYPrXMqB2VU12x5ptQ2IzhWrspzjgUqziAfmKtrlhwy+tB5GjN5CuQRlpSdTRyUrpvmy1DkE/Dv7gx7+KWxLS2EP7Raxywb7xScVC6qmjoKM5DZECdQ6SRFGwWX2oJhXLoDwdKW1a2IoOcTIireM0NYoH69c29YSBvkjPP+anYZg+mdnYNTBs9meTE8gheJHi+yj5SlQsNMMWQWHYHreTlNeNMrXrXzcYtAPSyTSPjKRVNe8FB9XdoQ== # gitleaks:allow
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
