apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: restic-rest-server
  namespace: restic-rest-server
  labels:
    app.kubernetes.io/name: restic-rest-server
spec:
  ingressClassName: infra-traefik
  rules:
    - host: restic.lab.hddq.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: restic-rest-server
                port:
                  number: 8000
