apiVersion: v1
kind: Secret
metadata:
  name: restic-htpasswd
  namespace: restic
type: Opaque
stringData:
  .htpasswd: ENC[AES256_GCM,data:m9vfgm3i5d660dWYDPEZhN7+xeiPOQOlJSyZJRmcKbuSe36bR7RJCdGmUQAX189MaO7rXmQNVts5N7RSbnGL5W6ZBw1FIC6LICp/crFBgu0azk7C7Epr1eBL1tK6hBuw/qHbYK/h8jt4odC65plt46sJLMEHGITu3ob3SyLMxYQW2Z12,iv:NKRNODq9HnfECY3MZTAW1haKVk9IVDOHROg0wkXMYl4=,tag:mGEK0s7wCPvfjSEdp39p/Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMmZlK05QNHE0WFo1RTUv
        RDRidjJnODBqUndtZ3J5RFFrTjA0bGlJZ2lRCkd0U01FZXlreTQ0Ly96bEpWSDhh
        eitocjA0eHdoSzU3YWZyU0tnWERQOHMKLS0tICtqT1ZtT2FCRTNKMEN2c240M3JC
        U1FFT3YxVWhub0NsdjB4VVdlc0FLVmsKk6y7Gy7iZeye2sb5IHcsuL+t4J3gavWc
        hFwx6WKBvf//XntPT93zwU2K0254jvisnZJpWlS4RyWxomXdpB2hhQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n0cqvlyfca7gjasrmj4668gn9e3pak8fep0e84cvnpc3srt8zffqn4fs74
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NXVzZko4ZmoyZzB4NTNx
        aEpEVmNDN2RCTDBDOUROUzJIN0txbFBNN1ZRClB2cGRIaW1tTS9jWmU5TzluMjhh
        NEpKOHdxM2lTWlJzcmlUV1J0RzRuQ00KLS0tIE9IUndmaFlpT2FuVk51bTFXanps
        R1ZSeWEzbFdqZFV1WkZPNTZ5Q3hZZmcKJqP/xZMZUbQi6fkdFKgB5F3qsgx9yjEA
        tx0YJCUi7WrhBOeNWroQFLE3MUyacYKJr16sd9Y253C2dM7FqL1nPw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10yse6kg99dwtsjaq4l7umdheecwsznpk4dnu76ff5jmjuka8uv9se4ysq2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T21:54:01Z"
  mac: ENC[AES256_GCM,data:CJF2CMxMrj9yUpO4V1wbFIZQ/25btAcIbeZfrPlzgk2/uUpvWdWgGWVhEStvoQcVHxqjT/Crh3ZNIXFFGxTFLiyha7B+RaTC0+lxl6JPLIrRbS8Ql1vCd5m8pJWLOC3ujv9VGgmn4RVkwO7Ln+OutHS2a4STfSfU49AeX85293Q=,iv:/6x8M0dXTD4pK6JtuYap2bPLitlAxa0PlfqY18fBASQ=,tag:CFi3aBbY1n5mNIRvtX0ugw==,type:str]
  version: 3.13.0
