apiVersion: v1
kind: Secret
metadata:
  name: audiomuse-secret
  namespace: audiomuse
type: Opaque
stringData:
  POSTGRES_USER: ENC[AES256_GCM,data:i9J1G8CIWrx3,iv:7jAKpXa7n1OO1wNMygq5t7qcCbhj3jwJ7fmiiiGR5R0=,tag:MILFXRWjdn0C26XvcxysLg==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:TUgtvwrZjPcUsrVWPz5K7oHRTRdBjjOeMtN7G7eptaIYXMNWFXi16wQFVGnUjq+VDgw=,iv:yX1Dlzu/NyC23ZIWarVdGy+q7eknatk3I+NGehw5QQw=,tag:XqaXB9Euz5BYVRURa1dyZA==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:A3qqxX9K7Sdv,iv:W1tCdiUiWP8t9y0+Lwy8dVPASVIcxwoAJdHhF3/oalk=,tag:pWWPqTTj/GXdWt5iaOAMUQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aEh1cFh3NVJFYWRoOHJ1
        ZDRuRlJYeEpmamRnSWVOU1U5YkNLL2EzVUd3Ci9hOTMrcGJSTXdpYTlCZ3JGeGQz
        blJYYThDMGdlWmFlU2dpa1hRS0NGTU0KLS0tIDZPTFlZTlJpOFlBN25nM3d2OGE3
        RnFRcnpjWmdqS1luTXlvR1FIQnY4eGcKVe4eknKNvwfuOyo5ObcLnxlK2JXMqcEd
        9etBfLeCJ2tB5fmg79aBVPxYNZpNGair3gITJtNCRI9usG4VjHYHcA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n0cqvlyfca7gjasrmj4668gn9e3pak8fep0e84cvnpc3srt8zffqn4fs74
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNnZIejZNa0hGeWFlQURy
        d3hmak9zRlFXWnVYYk1UWFlWOVgrZERrWW5vCjMwZXhEMzJKVlNuUm1QNzU1a0tP
        SlN2Z1Q1SlE4b1lqK0xJTlF5T2VjelUKLS0tIDdJRmZ1T3RXbzd5K09EdHZOVjZ4
        eTBuT1lMT0o0N21jVVBKMTBSZk4reUUK5Dz+yWDiW0HSUJnhvTB+AuqxoKMGxzhe
        WL7ygVLoicGUyom51U3tErYtpfYsuRJ3tQKVpwnm3jtrzOPk5nZQSg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10yse6kg99dwtsjaq4l7umdheecwsznpk4dnu76ff5jmjuka8uv9se4ysq2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-09T20:27:07Z"
  mac: ENC[AES256_GCM,data:PTDrjbg9Jz5iygDiMsvVMufr9twmekw9vI6t6pjtnII9dyKA/LzylvnG5PLHn+CL/69u780j+Dhj29D78Lq6pvyD9lJAmVC7wd+ilfuDZgeQ4Nd4JCOFY8o3064nuEy5Hvh+K+SDNuqxUTCR1xvubML8aO+6VszzqcLzumwFB/A=,iv:CA4v2CVDkbqioa2kqH7sur37Nylx4j1c4Slx6ibaAOE=,tag:6vbdnJdaAb00T88zRQXAYA==,type:str]
  version: 3.13.3
