apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: playground
spec:
  selector:
    app: postgres
  type: LoadBalancer
  loadBalancerIP: 192.168.41.16
  ports:
    - port: 5432
      targetPort: 5432
