---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: playground
spec:
  encryptedData:
    password: AgBL+Ko5nQuF1m75vCQBI7rP8iFqalv8Xy/GdZiC7ndj6y0pK04uXilryTbyIsrRmSbFPbG1EMTsfFNvj8B/8gonMhb4tMbL62NaC3TLazDkYMVMjJgcjSN7aQ4xKENyXjVBI9Hj2kKjbjjtDXk+H6WAEAeaSZAHIESh3FHvNgltfBiBBvk26JfwEqZmhNAedIFJB/MuUHamdFDYeBqKoJbgL9yzRsxMlHatbVwsfBCE9rZcnn5Rnle+zK/tWG5Roh7y/GwKLRPUytR3blv7pB/NLXoT7wmCYeC2oR536MFzJAYu8kY5ue6xycGHtUpYxMrflCCEQfAzBtTgCSXM+05lzoAu++heLpbjCc7GOgvvHTDqsAxYDuPylQeOquuIjjxpLFHB6lQkkw8UlHUqjLymDyGT5mImn95duwKnzm8Bk5s0TOhmvkkuikltYyYDS3noKNKw8rNi0Bo5E7c56xLYlMPmOd+rHTU9r9MPI9OAH7NtGFMwfm2i3JnS1MRVeWWaKQcWPiCMu0Hx7vMCo8BJMx/cts7fw34DbY1dEolFBKR2Y3GV5D7iVyD+CR9VtIjxzZjvDXguvb635aGuSa0U7h9R9nl46F1hI6gqwgFLvS1GOXSA6UOZUlTdHEYHsapBhaTH2nDQTaSx4pQbxug5mmj8BMmQfgYIRi268yq4vHGNYDGfcAg9tRC3J5pvhSpu2ptSgdC4hw==
  template:
    metadata:
      name: postgres-secret
      namespace: playground
