---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: default
spec:
  encryptedData:
    password: AgC6VyoGnrvDsg0DAfX9NefGSwiy/7h5fA5umCZs9whJ04lj5ur/ZyHSRVHpFfqa9vdS+BRSkKgFZEtWvYLLLFfq8ZT5NOmvJ39DRE3JggHCGrbDj5yRlCKnTGI3d350iCeslG1OdvwS5aanjgPR2Qsxdwd7iKaHhEz0QqjU7xUO3OC32uMyBEtdFj/HUaxS2wGYrHBE8OjtGCYGU/UGhnOW8DoX5FCaXh4lmFwBnGrf30U0SxePBFn6kDE1ONV6JirB5FEYcC1mi/7ZfJdWW7T6D5/3BlumqF84qvQ+X//NUOnmqdLL8/60Avw6pYfLt7Z0I1uYujW2iCFdOWeL2B47o0IlkrfbobaaFKZKB6WShI2n+HED1dD5UaSI2ikzziZK0D7zLTUkI1T9RRm6ayAuEyY7e4LXFsEy3C6OCzdaIuBAncrMSPfW46TYSZMaDRTOfm5yFNmhnXfJ/oUd1GeDxQUHCy0/pMYh4vxZNI8wGFF6COsr8KRYl8e+OAZqbdfxMHee3nZS5n5Rxd106VKE1n/qVdUjWr1ZfF4GT/RRpezaPlVwp26ZxvCv6F5T6FEQOxT35eq1RM3iUQN076D1RYL8UiKVBclc6Cv2fImXWpwA12XB5Cmokgipm/hMgwIOpQwMpazCLqh6sO31aqg0RaLcAa6paVAdJblZFi3gyRBtj3EzN2l1CiTtYvO5SAo=
  template:
    metadata:
      name: postgres-secret
      namespace: default
