---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: default
spec:
  encryptedData:
    password: AgBTQPJND7+L1302CO7XwlkH0G2HgBKKJrRLzle+wLkKH5aZCEk7y9KIc8ytcbsZuIwsxVIAb84PSFTzcWa9beNasgmm2IXMmwXhiaAixV9GsGs7bk75WPAlvQhVlIm6wiO6RjMl5BwE1EThIDn8YZO0xUrclJB0z/tKMwvNk9aQz7HjEMBl+vAcK7zxkk8AT7aJcChuuQG6NppDyZbsYe1qvSiw3j2ZfwrQLYzt/HfANZj+6V8p085EwfTrIEJEPTscdM9RqrnQxbPKqhOkdj4iVHH+Ka9lRagWeyNMuC1SvEoedVbIihuNcuzRzF/0iGKCj+N/IpCeg4JSw/uERcYckacZ3WPsoSDVDOcH86HLr05e5SIaZHDTeNdmqJrxz3c7cjJMukJ0JcCJQmuo85ykLaI3aYwJ8vXqqR/v8kPxeyclLs4Cme61WHFOmNfJGnk0Ee6whSvn8FCC7bHRKB2SLYId+jafiskBLN1XGPgtro6Viwe6fJ13AiewBWgD/vw2qDO6eT1eQqf1r+G3Ab1Fg6RdWuo5FBHp+i25uhZAtdbX/GyUQe9Z9n3YKU4LNz0le0KflQJNTCchWuo8SD1QscN8viYqBn9XMrb6rxCt1JvtPHWAO3UfUsYQvm8snwMOIT9+PTxt8mr+oOZhGHliBuWIyHy1CUm5+kSveGNJh80zdSluSpUwdcYSZ1P8k3b0IqDI6RnttQ==
  template:
    metadata:
      name: postgres-secret
      namespace: default
