homelab:
  metallb:
    myASN: 65001
    peerASN: 65000
    peerAddress: 192.168.20.1
    addressPool:
      - 192.168.41.10-192.168.41.250

metallb:
  speaker:
    # Allow MetalLB to announce BGP routes on single-node / control-plane nodes
    # despite Talos setting 'node.kubernetes.io/exclude-from-external-load-balancers'
    ignoreExcludeLB: true
  prometheus:
    serviceMonitor:
      enabled: false
    podMonitor:
      enabled: false
  frr-k8s:
    prometheus:
      serviceMonitor:
        enabled: false
