apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: monitoring
type: Opaque
stringData:
  admin-user: ENC[AES256_GCM,data:QqgaUTY=,iv:qtp/WxsEIdP1Q44ITvQd/DdTtcBYaJuNtC7G7TX0jJU=,tag:4A6DTX1P5cMdgnh2ZtsOCQ==,type:str]
  admin-password: ENC[AES256_GCM,data:XkiqRwKOE6BnyrwXD1CV7z+30nw4DqP860QP55rBr1ySC1u/Dz/v1w==,iv:gAvnePMiVbbfzsyqPMwPIMoow/AAWjBI/QLT+EUhb4s=,tag:Ij+/o8DUlfZZuEZoLPgApw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycTQvVmovN3NpYnQ4TEl2
        VDBGSVFzSzByNDROR0JLVy9paUZza1lEa1ZRCm5vUzl1OHVGanA4QkovNUNvaUtG
        NGxBWDVPa0FEeHBQUThvdy8yaUw0aHMKLS0tIDlpTE1yQ0gzZk9sbEFxRmF1dnBp
        Vm5CSmEyZXFITW1ZM3pHWDhsVDZxRkkKY1sGMXv1mB1hbIaE1DqJTJItD96KfSu/
        oAWMEY3stPQJ2TeULqCUvtGYEPXfNpmw0XhgN0Sf2lVZ8l0AFsi6BA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n0cqvlyfca7gjasrmj4668gn9e3pak8fep0e84cvnpc3srt8zffqn4fs74
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUWdHVzhOamZUdVRzdzlP
        S2xXaFdMUzNlVW82bE4ycDhTMlVsQyswOEhnClYxM1hsS0g4cGRCUzN6a0xXZWNC
        dFJLLzgxME1uaTJLTEp6MnppSmh2SmcKLS0tIDBpeHQyVFRNV0RBTy9RZWVEbVpV
        S3dNUlpzdVF5S1NPTHhXOXA2TGxRNTAKOYNY416i9uCL6DPVmJeVL1iJH9Nf6Gsr
        nspNUo6V6gpt0XTf5/hzaodMmcg/u8l0SWaJtzLaXUn8y5oeT5jTvg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10yse6kg99dwtsjaq4l7umdheecwsznpk4dnu76ff5jmjuka8uv9se4ysq2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T21:14:38Z"
  mac: ENC[AES256_GCM,data:bm58G489Nb+KIVnlgRprDhILt1inv2NOtwAYNMRyom31C8NHvphYX6ZdYrFqD3uh5wJ9R8fGx1ke2/X2q9ZVvPHlQfzahOlf767JmKF1z4gnhP8ZgwQQhPnD7IEThGf5n+b9/hmWH38DW/fa5dE78ZK8OdApxPkD74OxTS66o5o=,iv:u0+AtEkQWhHa78CSM8noSg4RpKdvaCqfDnn/yg3hNCo=,tag:Oh6R8gf5tcAoLctlW6MR2Q==,type:str]
  version: 3.13.0
