apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shelfbridge-pvc
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 1Gi
