apiVersion: v1
kind: Secret
metadata:
  name: shelfbridge-secret
  namespace: audiobookshelf
type: Opaque
stringData:
  SHELFBRIDGE_USER_0_ID: ENC[AES256_GCM,data:Cs9ELg==,iv:3Df5gSiE+6tD/uHlyLnLeG+v8y9eT/jp7fUrfNJB6Wg=,tag:AWEVrGfqxcH1lDoaSxTocw==,type:str]
  SHELFBRIDGE_USER_0_ABS_URL: ENC[AES256_GCM,data:pN84sKRvhpQ5SQ+kJqMENJ88MsNR7HC6/nGwEKGvr7YWZGZV8r8mA98BKIpq1E6LtOfb/JnUowGW,iv:6BzTGdsLvFD/quBKKmWK9ux73P+Pm8fhycn3hk7kzxs=,tag:F61OG1ML4QGP2oYsVN2w4w==,type:str]
  SHELFBRIDGE_USER_0_ABS_TOKEN: ENC[AES256_GCM,data:sAsmuMaPkDga5IDoq08sa7/NRukOttb0oYtjutd6To4mmKtIsczETD86csfU2OehVUlq4Z7zNfZskIF+K5WjRQAyDSb+IsasuyuQFJ/2UGj+cfzaEobe1pcy02y5WdhzkfTneE69Oso7vvIsidr7uY3FknCdumdHAkJ+XVLuhU0vcwhxyui5L+cuIbaumO0aF/b2oSNtxUfCBarxT5s1GtDloq0Nt+4iEgrUyAwADpbkUfbzYQvCzOpczrjNM4dsYA==,iv:WK/hGEVfuomR91v9KTvVzEPP3zpwCVve26+Sr4qYY5I=,tag:k9NWLdr48K6SLOsSWmMBpQ==,type:str]
  SHELFBRIDGE_USER_0_HARDCOVER_TOKEN: ENC[AES256_GCM,data:aGfOWp75f3cWjEyUtAjgk3FOD+vPDrd4o0IqTCkmzA0uayHaXm90KE+Geur/2wwiwc/f,iv:HhUb/vhhoyKSI9s7of0NLH8vllUFslYCwPBmIy35NYU=,tag:e0Upops/u27HHl6JuQhY8Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVclJlOXAyMXk3U0FFdktG
        cTZuNzhrZlU4UVUzcWNCc1JjVzlLMEF0a0NNClp2YVY1UFNjUXZoN2t2Ym1KRkJ1
        YkR6b1ovUlhOOG1wcXdJZjlpd21sY1UKLS0tIGY5cThycGw1N3hWcmJIdGhjMHBG
        TEwwdlFWVmVFZjlLMEZneDRsT2EyclkKhtv9UIc2YFLrinFm6GJvZN2I7FucJhll
        A63XoCwncM568SzuSthXxXZiO55IhtEZFAC2oJbGMvizkMVuagI1zA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n0cqvlyfca7gjasrmj4668gn9e3pak8fep0e84cvnpc3srt8zffqn4fs74
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Y3lpRGFjS1VOU0ZON1lD
        V2tZSFh0NUpKZ3c5TDZMZ0xRWTdINy9Nc2gwCld0clF1Vmg1VXhWNWsyOElnQWc2
        R0g4d2dqOHhFL2M1UmxRN2xRYzQ0L2cKLS0tIFI0TUsyTFhyWDlaSnJ1M3gzeE53
        UUFYTlBHa3Z2cU9JQk1YZ0swOVZCcUUKY+hwOxiHKhV7Sx7ub4MaOTP8wuVMrp/n
        etJAvQF4ZOyTl71e1lQF32L+zgIG7MZtFyh4Cl4JeatXxs2J0xzFtg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10yse6kg99dwtsjaq4l7umdheecwsznpk4dnu76ff5jmjuka8uv9se4ysq2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-27T00:16:21Z"
  mac: ENC[AES256_GCM,data:dW3GbKf/4us3bjUK+JZrUKi5RfgwQSVJHi7erNofs0qruTTikzohnGHygjIzVkHQwfeGl+RyAHDhl0uVRec2bejTuTBvK69sJ+a+d702GeDqByKlgDc7YeqVq/HMVGktDD3p+qpoVtv3kzZYGJMMsw5YXiEnY0/DZhys37EftFw=,iv:jviywO9yRvTr97uEP8eYBTFSXOUctQl5BoPyzl5A3xo=,tag:NnBNWQCyA2onyLY9D8o7AQ==,type:str]
  version: 3.13.3
