apiVersion: v1
kind: Secret
metadata:
  name: k8up-secret
  namespace: k8up
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:GLFIANozZK0H2eHF,iv:F7E9sBb15nBqBYacVMGOcpup9xD9sFt+BmZC8FlZA68=,tag:wRb14gj8v8igya885k1jkg==,type:str]
  s3-access-key-id: ENC[AES256_GCM,data:y7N9YCZGNnmv8+En1+PIayEB/b7KtbKaFnY=,iv:susxj3KlYHcY+c0y2/dK3quI8vXYwILwPWWGyTm+6po=,tag:CPFmIr2qxfzSAXejacPIMw==,type:str]
  s3-secret-access-key: ENC[AES256_GCM,data:OpmzkQRf+iWcwWcXR7FunsFD7Lz3umDR+ZvuTO0J9vnVBu/6kjUMuaVe3GJB5hqEV4HsZemH2f8SWD16ROV3Yg==,iv:cO9BfWalr4Mlr/zcNC4EkuqmEvY2v3OBqn78RQFA1CU=,tag:+F+eEw83rWSSlzu5YTBUww==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpK2VCV1kyTXhpb2tiSUJF
        SG1meGk2bnlTN3hXT0xqSXgyLzhnWmh0VldnCkVmdU1zaFloT0EwbG1TSWtQU1pR
        c1dEVGVpTGVqRE5KYUNGcTM2VTFiaGsKLS0tIFFZbkUwVjVWSGk1WSthbE8vQjBP
        Y05NQ1c2SUJWelZiNUNEVSt0T1hCZTgK8GAUZv6HuH+BnCY739vOjXcKb/gSGkMb
        llwx4t3zEB/bTNi5tw6TjzWugB22Nv9N7YDF2wlXdTqOip06z7UApg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1m8j9egmweu9c8cpz2yejsulpzy82227eceh9awergehk5pflwfsslu4nah
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-25T21:03:05Z"
  mac: ENC[AES256_GCM,data:VIG4JF9V/ncCMXoA5Pk9/s9nujpI2kQr/LCBXRqz+jPAvVcSErDaFuErgXK+iYhsQyOtruMbxmpq+lVy+f/zuSRovAWIgScraPmiH2BlyGnv4jbaGyAAb7tESg8cKI3Qr/thF6o5mHJz+5lWNKyXfvt4VmNugFuXZk2AzNQ0e70=,iv:1AVYU6vFClQMG30bVKGmhLbVdY2RNVW8xzTTTfrrmGg=,tag:L5G9yYRCUxgw/Wzx9Bo2eg==,type:str]
  version: 3.13.2
