apiVersion: v1
kind: Secret
metadata:
  name: k8up-secret
  namespace: k8up
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:moQjheJZc6rHKh6OcJE4zGlx7y8oLFInQLIZtlGAy859UHZWVCXGWikzS2p333A82LEw3WcTXylM2y9vJU9EQA4Z0w==,iv:laXgGmZ56rf/2Xu0sLV2yFxvHxWd1QeCvsrC4JecvLU=,tag:GMsnQmD4aCIA35AuK5XERA==,type:str]
  s3-access-key-id: ENC[AES256_GCM,data:+5fKCdLkGO/af88Jz4OWDnV8L4ZcppnVqbM=,iv:1baV2r5KjB0ZWSTMya/6XoyqWleX2NN2JPKhBHSE+QE=,tag:MNDKV6KTlOJSfS9WaSC09A==,type:str]
  s3-secret-access-key: ENC[AES256_GCM,data:YZRijBWxp63i6avGbhrM7fnrbZ6kWT6jwaFqyKZ+NxbrICDIZRYQsAQonZAZsDGMP9x/VBHd+uma33uuuFCeSw==,iv:BQmhf2XfMZvAIo757E65ZOZDIVqcJwRkqVWgJEmDJs0=,tag:80qt9axBXXi6oDdMUZYlag==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZaTN0UjI2emVPOUJsTFF1
        bkdNOGV2THBEY3hOVitmTTd6NGhYZDMxOWc0CjlhOC9UTzJnYllhWS9oekc0ZXBN
        N1E4WE5WRndWQ0srcFl0ejJFSXl1cE0KLS0tIENTOCtlUTVaaFBaOVU5ZVdqeity
        SWxsWFZkVlAyWmlldTA3SDEvSHBJVkkK1RlY7egkIIaqtq4sxmysjodXVTXFz7o4
        Z8az5xZDo+HU5rlPURWnraLYzpVQTV4+mPVdFmFFORRINbSc9FMOCw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n0cqvlyfca7gjasrmj4668gn9e3pak8fep0e84cvnpc3srt8zffqn4fs74
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCV1oyaHFLcjhPeWV3SnNk
        M2gwR210dTU3anJxSUhIZzZpVTRlMG5qY1hNCmluczFTNnRHNUVBVGsxWE1yaGVa
        OUVHR3N2WXhsNFNzRTlJWVIzendtYXcKLS0tIE5iRExzYllXaU5WbVB1c0VYVENz
        aXdDa3IrekEyUndubEV1K1FuM1hib2sKpLcy4OkW8IAIYSIUKwRLPTjXYJh4WLs8
        73NLHpTGiwRTCSUApAjigwgMeEGl7wBbzCKNzjFTDOs6UFxK+rG3Cg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10yse6kg99dwtsjaq4l7umdheecwsznpk4dnu76ff5jmjuka8uv9se4ysq2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-27T20:09:29Z"
  mac: ENC[AES256_GCM,data:Zo6BZAp9xHjtxnte4jJYxnJUOftLan6I8ueGy7VuF0jcdzofgFfpgIqBYJ7f66bOOr2CkLnDw4mHkFvJKHPr2iy+yys/ouTPsiJwKBU9Noo/Q/pf4J/DQfGEA2d+a3RtZbC508Gl2yCXDTRZyBgdMTeMM8D5xQdswks3oVwJsCg=,iv:vnxqb6bJ298OqrMx/gIafpYpCs5TH9sjqEgjlYn7DcY=,tag:AAjbI4xeC6XK7LsBKTn4eQ==,type:str]
  version: 3.13.3
