apiVersion: v1
kind: Secret
metadata:
  name: k8up-secret
  namespace: k8up
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:GLFIANozZK0H2eHF,iv:F7E9sBb15nBqBYacVMGOcpup9xD9sFt+BmZC8FlZA68=,tag:wRb14gj8v8igya885k1jkg==,type:str]
  s3-access-key-id: ENC[AES256_GCM,data:y7N9YCZGNnmv8+En1+PIayEB/b7KtbKaFnY=,iv:susxj3KlYHcY+c0y2/dK3quI8vXYwILwPWWGyTm+6po=,tag:CPFmIr2qxfzSAXejacPIMw==,type:str]
  s3-secret-access-key: ENC[AES256_GCM,data:OpmzkQRf+iWcwWcXR7FunsFD7Lz3umDR+ZvuTO0J9vnVBu/6kjUMuaVe3GJB5hqEV4HsZemH2f8SWD16ROV3Yg==,iv:cO9BfWalr4Mlr/zcNC4EkuqmEvY2v3OBqn78RQFA1CU=,tag:+F+eEw83rWSSlzu5YTBUww==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJb0w5eGFkdjdQbzE1MFNz
        bUlQYllzYnNtMTE5SWExTUpDaGI4YVZuYXg4CkphdHV1OTl5eW5FVVJybjZncm81
        TVhQQkZFdzMyRHNkSS92aUpqNTVMeFkKLS0tIGRmMFZVYVVGRkFURmJJcVE3Z21x
        K2pqVUdEa0tGOFhrYVZmV2lsa2ppd2sKDvA1JJNfKYwt0t5rkxm9CpF3q1gsYoFF
        LR7UJsOgoUNKWpdVlBWrYSFSu33BUeMZSImNzxr4Yraqq5NcCVS9Sg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n0cqvlyfca7gjasrmj4668gn9e3pak8fep0e84cvnpc3srt8zffqn4fs74
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbXJsYU5wN2V4bzQ3eGpQ
        enE3c3UvcHRDUGltMWVReFd1YTBtSmhrWmlvCjljTTN2ZUJrMHhObE03bGFSbWw1
        MjF0cEVxT01yVU13c1NxWVJpQ21FakEKLS0tIFBJOTNWVDJJTi9UQTN6eHZCS01v
        RncvaHh3MVRnOXd0NWVaL09tMUF0WmsKQ8StONUY2S+LXFGYT3b3Ukb0eMIvwdiU
        utEk3cudkNHOkUoQqfsYSFj6H3t0ErNXU3ovuvJDxjm6/Rs54R7+QA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10yse6kg99dwtsjaq4l7umdheecwsznpk4dnu76ff5jmjuka8uv9se4ysq2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-25T21:03:05Z"
  mac: ENC[AES256_GCM,data:VIG4JF9V/ncCMXoA5Pk9/s9nujpI2kQr/LCBXRqz+jPAvVcSErDaFuErgXK+iYhsQyOtruMbxmpq+lVy+f/zuSRovAWIgScraPmiH2BlyGnv4jbaGyAAb7tESg8cKI3Qr/thF6o5mHJz+5lWNKyXfvt4VmNugFuXZk2AzNQ0e70=,iv:1AVYU6vFClQMG30bVKGmhLbVdY2RNVW8xzTTTfrrmGg=,tag:L5G9yYRCUxgw/Wzx9Bo2eg==,type:str]
  version: 3.13.2
