apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:YzPSKQzTvXDzoR3d6wYQPd0Z+uaxVVto3FJ1dcnmiuEQEpIXccxN7XuBadvqH3u99VxV+dU=,iv:wshatLVlUPNz8qrTWUDfCEW878jBJpJW/ONrU10BS+A=,tag:nBaxO0Hwe6w7NcjTFZ5lEg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ0ppdW5WUzB1TVFKOVRY
        ZzRHd0NPMHVrMVY0WmRQZ2VvNXRXYXBqOVNJCkYzWU5sLzlkRFdhSjYvT0JQaVpj
        SzhKY0VqQW1hMEtpNWhTU2krZHcxcHcKLS0tIEZ5UGdhS2xldnJtQ0JVZ0lCNHM2
        QmhaVVJOa3ZkQzQrRk8xRnpIcTBuQnMK7vwjgTPjHRHRaCQTymRNW3gi5xCRgMnw
        uRhghZuvKHrM6cE3/kpCoNO2+NEA3fLC4sZOeF+Gm2W8ib9Ah7vquw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1m8j9egmweu9c8cpz2yejsulpzy82227eceh9awergehk5pflwfsslu4nah
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-28T23:04:14Z"
  mac: ENC[AES256_GCM,data:Qpn3VhWUYt/oCBf1BRHd/B6AfxnAT6T/iTNKEmbTeZBKw1meCmeXBA8SCdxAhtZXoU1d0rCIWYRmP139F4I5Gn/EKp0arRU1Y5PDa/SSwF4NLE7po7FvmDHYJhFYPJ8pT0qID4H8sUwFoIcvoPPkL62I+3+ojyTMDwI+pjLif2M=,iv:vY3BMPoaSaDpiDLOMMqnrQupJnMN4PXylBPysD3YJUo=,tag:lTC2uYG6ZiROSpf/LqOtMA==,type:str]
  version: 3.13.1
