apiVersion: v1
kind: Secret
metadata:
  name: immich-postgres
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:vj82AcELaE+3HZVcYytyJ35mo1wTnkfnKNLdlwLHI3XcIkTNu2kigzx78zkFwJpizgRP656MXfTKF1u70bHq0A==,iv:+swW7mAXhogGewHEEewxWoTDjmINvJ/rVLzJSyZLdrA=,tag:t3B45hy7SU/bevVZXbqK/Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJYjM1Z2dTM0JaMkpzSlhZ
        NkhERHZwVnd6VW5KbmEvMHZ6RHNTTUhuYXk0CnJFV0ZIU0dTbmo3RVk5b3JFcVBB
        bTVQZW5WT0dxTUE1ek5FZkc3RHI1MmcKLS0tIEFUNExKZ0dKQUpGTEdZUnUrOHdn
        T1l5OXplUnlhVEk0eFpRcjdtWXgvMjAKwbKM4pXtS67icL8vLPMrLhWp3nWlS/ZZ
        K0u6jNEKcIE8fQu0g4ovjLZRnNvGw9X39o+RLDY9GTwD7g06FEA4kQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1n0cqvlyfca7gjasrmj4668gn9e3pak8fep0e84cvnpc3srt8zffqn4fs74
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEa3NJNUZCWWMyNnowaDhL
        aWRuUkl5cEhVeGVsZHVhV3hVZjI5R1ZKWUVzCnZjK3VLL3Y5RWx4aEc2RUhQbno1
        YVUzR1A3d3FrVFBvK1ZydkZmK2dGa3cKLS0tIEVUc3ByRkdmR3d0RWgrb2tNYU5P
        TFdlQTdwM3lCajc2Sis1VUVqUVJudjgKxY7Kwk8cvdUYOEyhSBoJhK/LUi6hHtYL
        aHnGq/NWuaqoc3JML295nP4kRL76J/Egu89PbK58+35AAd/lfmNyxg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10yse6kg99dwtsjaq4l7umdheecwsznpk4dnu76ff5jmjuka8uv9se4ysq2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-03T17:19:43Z"
  mac: ENC[AES256_GCM,data:H4GaLuq++4d0G1+KGZ0AlW7OBksTHtaNrUwNrwZxvC3mUP0cwSYMLfriLEne+hCeNBzM5XMxGwh2uk48bMoss7fjybAPLH+SGRcdyf9Ek4E/By2z70q9JXmCpthGJV1QPaHzqSqyH8dn5E7SRLMzJBaN2pdbsu44sBbh7VRv/dI=,iv:8HAI7WCR5FcEvfOmLPHNn1rZoo14uqq7aiMcCPD7kGo=,tag:5N2aIpOZFgvuU0T1DnJncQ==,type:str]
  version: 3.13.3
