apiVersion: v1
kind: Service
metadata:
  name: feishin
  namespace: feishin
  labels:
    app.kubernetes.io/name: feishin
spec:
  type: ClusterIP
  ports:
    - port: 9180
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: feishin
