name: CI - Ansible

on:
  workflow_call:

jobs:
  ansible-lint:
    name: 🦅 Validate Ansible
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Force install Ansible requirements
        run: ansible-galaxy collection install -r ansible/requirements.yaml --force

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v26
        with:
          args: "ansible/"
          setup_python: "true"
