name: CI - gitleaks
on:
  workflow_call:
  schedule:
    - cron: "0 0 * * *" # Daily scan

jobs:
  scan:
    name: 🕵️ Gitleaks Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      pull-requests: read
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
