name: CI - Kubernetes

on:
  push:
    branches: ["master"]
    paths:
      - "apps/**"
      - "infrastructure/**"
      - "bootstrap/**"
      - ".github/workflows/ci-k8s.yaml"
  pull_request:
    branches: ["master"]
    paths:
      - "apps/**"
      - "infrastructure/**"
      - "bootstrap/**"
      - ".github/workflows/ci-k8s.yaml"

jobs:
  kubeconform:
    name: ☸️ Validate K8s Manifests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run kubeconform
        uses: docker://ghcr.io/yannh/kubeconform:v0.7.0-alpine
        with:
          entrypoint: /kubeconform
          args: >-
            -summary -strict
            -ignore-missing-schemas
            -ignore-filename-pattern Chart.yaml|values.yaml|.trivyignore.yaml
            -schema-location default
            -schema-location https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json
            apps/ infrastructure/ bootstrap/

  trivy:
    name: 🛡️ Security Scan (Trivy)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@0.35.0
        env:
          TRIVY_IGNOREFILE: apps/.trivyignore.yaml
        with:
          scan-type: "config"
          hide-progress: true
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
          scan-ref: "apps/"

  pluto:
    name: ♇ Pluto (API Deprecations)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Download Pluto
        uses: FairwindsOps/pluto/github-action@v5.23.0

      - name: Use pluto
        run: |
          K3S_VER=$(cat k3s_version.txt)
          echo "k3s version: $K3S_VER"
          pluto detect-files -d . --target-versions k8s=${K3S_VER%+*}

  helm-lint:
    name: ⎈ Helm Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Run Helm Lint
        run: |
          for dir in infrastructure/*/; do
            if [ -f "${dir}Chart.yaml" ]; then
              echo "Linting $dir"
              helm dependency update "$dir"
              helm lint "$dir"
            fi
          done
