name: CI - Global Lint

on:
  workflow_call:

jobs:
  yaml-lint:
    name: 🧹 Lint YAML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint
          file_or_dir: .
          strict: true
