name: CI - ShellCheck

on:
  workflow_call:

jobs:
  shellcheck:
    name: 🐚 ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: .ansible
