name: CI - Talos

on:
  workflow_call:

jobs:
  validate:
    name: ⚙️ Validate Talos Configurations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install talosctl
        run: |
          talos_version="$(yq '.talosVersion' talos/environments/staging/topf.yaml)"
          curl -fsSL -o /tmp/talosctl "https://github.com/siderolabs/talos/releases/download/v${talos_version}/talosctl-linux-amd64"
          sudo mv /tmp/talosctl /usr/local/bin/talosctl
          sudo chmod +x /usr/local/bin/talosctl

      - name: Install topf
        run: |
          curl -fsSL https://github.com/postfinance/topf/releases/download/v0.6.0/topf_linux_amd64.tar.gz | tar -xz -C /tmp
          sudo mv /tmp/topf /usr/local/bin/topf
          sudo chmod +x /usr/local/bin/topf

      - name: Install yq
        run: |
          curl -fsSL -o /tmp/yq https://github.com/mikefarah/yq/releases/download/v4.53.3/yq_linux_amd64
          sudo mv /tmp/yq /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Run Talos Validation
        run: bash scripts/ci/talos-validate.sh
