name: CI - YAML & K8s Validation

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  yaml-lint:
    name: 🧹 Lint YAML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint
          file_or_dir: .
          strict: true

  kubeconform:
    name: ☸️ Validate K8s Manifests
    runs-on: ubuntu-latest
    needs: yaml-lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run kubeconform
        uses: docker://ghcr.io/yannh/kubeconform:latest-alpine
        with:
          entrypoint: /kubeconform
          args: >-
            -summary -strict
            -ignore-missing-schemas
            -ignore-filename-pattern Chart.yaml|values.yaml
            -schema-location default
            -schema-location https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json
            apps/ infrastructure/ bootstrap/
  trivy:
    name: 🛡️ Security Scan (Trivy)
    runs-on: ubuntu-latest
    needs: yaml-lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@0.69.1
        with:
          scan-type: 'config'
          hide-progress: true
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          scan-ref: 'apps/'
